.TH MOUNTD 8 "Jan 23, 1993"
.SH NAME
mountd \- NFS mount daemon
.SH SYNOPSIS
.nf
.B /etc/mountd [-f exports-file] [-n]
.fi
.SH DESCRIPTION
.I mountd
starts
an user-level mount daemon.
.LP
.IR Options .
The
.B -f
option specifies the exports file, listing the clients that this server
is prepared to serve and parameters to apply to each such mount (see
exports(5)).
By default exports are read from
.IR /etc/exports .
The
.B -n
options specifies that mountd should accept mount requests from insecure
ports.  This is necessary for some older clients.
.SH "SEE ALSO"
exports(5), nfsd(8), ugidd(8C)
.SH BUGS
The current implementation (still) does not keep track of remote mounts.
