.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH CHSH 1 "26 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
chsh \- change shell in password file
.SH SYNOPSIS
.BR "chsh [ " name " ]"
.SH DESCRIPTION
.B chsh
will change the login shell for the specified user (only the superuser is
permitted to change shells for other users).  If the user is not root, the
user is first prompted for the password.  Then the current shell is
displayed, followed by a list of allowed shells (from
.IR  /etc/shells ).
The user is prompted to pick a new shell from the list.  The shell is then
changed in the password file.
.SH FILES
.I /etc/passwd
.br
.I /etc/shells
.SH "SEE ALSO"
.BR passwd (1),
.BR chfn (1)
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
