.TH MESG 1
.SH NAME
mesg \(em control write access to your terminal
.SH SYNOPSIS
.B mesg
.RB [y|n]
.br
.SH DESCRIPTION
.B Mesg
controls the access to your terminal by others. It's typically used
to allow/disallow others users to \fBwrite(1)\fP to your terminal.
.SH FLAGS
.IP y
Allow write access to your terminal.
.IP n
Disallow write access to your terminal.
.IP [none]
Prints out the current access state of your terminal.
.SH SEE ALSO
write(1),
wall(1).
.SH AUTHOR
Miquel van Smoorenburg, miquels@drinkel.nl.mugnet.org
