#! /bin/csh -f

set tmp = /tmp/$$
cp /dev/null $tmp
grep "^class" *.h | \
    sed -e 's/.*class \([^ ;\*]*\).*$/\1/' | \
    sort | uniq | fgrep -v "(" >> $tmp
sed -e 's/\(.*\)/#define \1 _lib_dp(\1)/' < $tmp > "_defines.h"
sed -e 's/^/#undef /' < $tmp > "_undefs.h"
rm $tmp
