.TH BINCHECKR GNUCHESS
.SH NAME
bincheckr
.SH SYNOPSIS
.B bincheckr
filename
.SH DESCRIPTION
.I Bincheckr
is a program to check the opening book of 
.I gnuchess
for eficiency.
.PP
.I bincheckr
accepts a binary book file containing chess moves and checks the file for run length.
It prints statistics for the binary book file. 
.SH "FUNCTION LETTERS"
.SH BUGS
.PP
.fi
.SH SEE ALSO
.nf
gnuchess(6)
chesstool(6)
xboard(6)
.fi

