.TH CHECKGAME GNUCHESS
.SH NAME
checkgame
.SH SYNOPSIS
.B checkgame
filename
.SH DESCRIPTION
.I Checkgame
is a program to check the output of 
.I gnuchess
for illegal moves.
.PP
.I checkgame
accepts a 'chess.lst' file containing chess moves in algebraic notation and checks the file
for illegal moves. 

Castling and en-passant moves are allowed. But in castling moves no check is made whether
the pieces have moved before or whether a intervening square is under attack.

.SH "FUNCTION LETTERS"
.TP
.SH BUGS
.PP
.fi
.SH SEE ALSO
.nf
gnuchess(6)
chesstool(6)
xboard(6)
.fi

