.TH GAME GNUCHESS
.SH NAME
game
.SH SYNOPSIS
.B game
[start [end]]
filename
]
.SH DESCRIPTION
.I game
creates a board by board postscript output file on stdout for all or part of a chess game.
Input is a 'chess.lst' file output by
.I gnuchess.
When combined with the 
.I ChessFont
file and sent to a postscript printer it will show all boards in the range specified.
For each board the move and the current score are also printed.
.B ChessFont
is courtesy of Andy Walker, Maths Dept., Nott'm Univ., UK. (anw@maths.nott.ac.uk) 
and is copyrighted by him. 

Moves starting at 
.I start
and ending with 
.I end
are printed. If no start or end is given all moves are shown. If only 1 number is given it is assumed to be the start.

To use:

.B 	game gamefile >tmp

.B	cat ChessFont tmp | lpr

.SH "FUNCTION LETTERS"
.TP
.SH BUGS
.PP
.fi
.SH SEE ALSO
.nf
gnuchess(6)
chesstool(6)
xboard(6)
.fi

