.TH GNUAN GNUCHESS
.SH NAME
gnuan
.SH SYNOPSIS
.B gnuan
.SH DESCRIPTION
.I gnuan
produces an analysis of a chess game.
For each move it shows the move, the score and the principle variation selected
by
.I gnuchess

.I gnuan
prompts for input parameters when it is invoked.
Input file is a
.I gnuchess
list file.
.I gnuan is a modification of the gnuan program from
Truman Collins (tcollins@pdx.mentor.com).
.SH "FUNCTION LETTERS"
.SH BUGS
.PP
.fi
.SH SEE ALSO
.nf
gnuchess(6)
chesstool(6)
xboard(6)
.fi

