.TH POSTPRINT GNUCHESS
.SH NAME
postprint
.SH SYNOPSIS
.B postprint
filename
.SH DESCRIPTION
.I postprint
creates a board by board postscript output file on stdout of the contents of the 
.I gnuchess
persistent hashfile.
The hashfile contains information from previous games saved by 
.I gnuchess.
For each position it prints the board, the best move for that position
and the search depth that generated the move as well as several flags
indicating information about the position.
Flags show whether the score is a true score, or an upper or lower bound on the score
and whether or not kingside or queenside castling was legal.
When combined with
.I ChessFont
file and sent to a postscript printer it will show all boards in the range specified.
For each board the move and the current score are also printed.
.B ChessFont
is courtesy of Andy Walker, Maths Dept., Nott'm Univ., UK. (anw@maths.nott.ac.uk) 
and is copyrighted by him. 

To use:

.B	postprint >tmp

.B	cat ChessFont tmp | lpr

.SH "FUNCTION LETTERS"
.TP
.SH BUGS
.PP
.fi
.SH SEE ALSO
.nf
gnuchess(6)
chesstool(6)
xboard(6)
.fi

