.TH olwmslave 1 "22 Feb 1991"
.SH NAME
olwmslave - helper program for olwm
.SH SYNOPSIS
.LP
.B olwmslave
.SH DESCRIPTION
.B olwmslave
provides functionality for \fBolwm\fP(1) that is better done
via a separate program, such as the Spot Help window.
.LP
.B olwmslave
is started by \fBolwm\fP(1) and is not intended
be used directly.
.SH "SEE ALSO"
.BR olwm (1)
