#! /bin/sh -v
xmessage this is standard usage, message on the command line
echo this is a message from standard input | xmessage -file -
xmessage -file Imakefile -buttons print,me -print
xmessage -buttons "" no buttons, use delete window from window manager
xmessage -buttons default,other -default default Type Return for the default
xmessage -buttons many,buttons,determining,the,size,of,the,window short msg
xmessage -buttons 14:14,102,3:3,27:27,105 pick a number; echo you picked $?
# fun with resources...
xmessage -buttons "" -xrm '*message.borderWidth: 0' \
	-xrm '*Translations: #override <BtnDown>: exit(0)' \
	click here to dismiss
