.\" -*- nroff -*-
.TH E2FSCK 8 "Mar 1993" "Version alpha 0.2c"
.SH NAME
e2fsck \- check a Linux second extended file system
.SH SYNOPSIS
.B e2fsck
[
.B \-acdflrstv
]
[
.B \-b
.I filename
]
.I device
.SH DESCRIPTION
.B e2fsck
is used to check a Linux second extended file system.
.br
.I device
is the special file corresponding to the device (e.g /dev/hdXX).
.SH OPTIONS
.TP
.I -a
Automatically repair the file system without any questions (use
this option with caution).
.TP
.I -b filename
Read the bad blocks list from
.I filename.
.TP
.I -c
Check the file system for bad blocks.
.TP
.I -d
Print debugging output (useless unless you want to find a bug in
.B e2fsck
).
.TP
.I -f
Force checking even if the file system seems clean.
.TP
.I -l
List all the file names in the file system.
.TP
.I -r
Interactively repair the file system (ask for confirmations).
.TP
.I -s
List the super block before checking the file system.
.TP
.I -t
Check the file system for bad blocks.
.TP
.I -v
Verbose mode.
.SH AUTHOR
.B e2fsck
is based on
.BR efsck (8)
which is based itself on
.BR fsck (8)
written by Linus Torvalds <torvalds@cs.helsinki.fi> for the
minix file system.
.br
Remy Card <card@masi.ibp.fr> has adapted it for the second extended file
system and is maintaining it.
.br
Wayne Davison <davison@borland.com> has contributed lots of nice
features.
.SH BUGS
The lost+found management has not been tested.
.br
.B e2fsck
cannot repair corrupted super block or block descriptors yet.
.br
Please report other bugs to the author.
.SH AVAILABILITY
.B e2fsck
is available for anonymous ftp from ftp.ibp.fr (132.227.60.2) in
/pub/linux/ALPHA/ext2fs.
.SH SEE ALSO
.BR mke2fs (8)
