.\" -*- nroff -*-
.TH MKE2FS 8 "Mar 1993" "Version alpha 0.2c"
.SH NAME
mke2fs \- create a Linux second extended file system
.SH SYNOPSIS
.B mke2fs
[
.B \-c
| 
.B \-t
|
.B \-l
.I filename
]
[
.B \-b
block-size
]
[
.B \-f
fragment-size
]
[
.B \-i
.I bytes-per-inode
]
[
.B \-m
.I reserved-blocks-ratio
]
[
.B \-v
]
.I device
[
.I blocks-count
]
.SH DESCRIPTION
.B mke2fs
is used to create a Linux second extended file system on a device (usually
a disk partition).
.br
.I device
is the special file corresponding to the device (e.g /dev/hdXX).
.br
.I blocks-count
is the number of blocks on the device.  If omitted,
.B mke2fs
automagically figures the file system size.
.SH OPTIONS
.TP
.I -b block-size
Specify the size of blocks in bytes.
.TP
.I -c
Check the device for bad blocks before creating the file system.
.TP
.I -f fragment-size
Specify the size of fragments in bytes.
.TP
.I -i bytes-per-inode
Specify the bytes/inode ratio. 
.B mke2fs
creates an inode for every
.I bytes-per-inode
bytes of space on the disk.  This value defaults to 4096 bytes.
.I bytes-per-inode
must be at least 1024.
.TP
.I -l filename
Read the bad blocks list from
.I filename
.TP
.I -m reserved-blocks-ratio
Specify the ratio of reserved blocks for the super-user.  This value
defaults to 10%.
.TP
.I -t
Check the device for bad blocks before creating the file system.
.TP
.I -v
Verbose execution.
.SH AUTHOR
.B mke2fs
is based on
.BR mkefs (8)
which is based itself on
.BR mkfs (8)
written by Linus Torvalds <torvalds@cs.helsinki.fi> for the
minix file system.
.br
Remy Card <card@masi.ibp.fr> has adapted it to the second extended file
system and is maintaining it.
.br
Adam Richter <adam@soda.berkeley.edu> added the automatic file system
size detection.
.SH BUGS
.B mke2fs
accepts the -b and -f option but currently ignores them because the new
extended file system does not support variable block sizes nor fragments
yet.
.br
The -g option has been added quickly and has not been tested.
.br
There may be some other ones.  Please, report them to the author.
.SH AVAILABILITY
.B mke2fs
is available for anonymous ftp from ftp.ibp.fr (132.227.60.2) in
/pub/linux/ALPHA/ext2fs.
.SH SEE ALSO
.BR e2fsck (8)
