.\"{{{}}}
.\"{{{  title
.TH BITMAPTOC 1
.\"}}}  
.\"{{{  name
.SH NAME
bitmaptoc \(em convert a MGR bitmap file into C code
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B bitmaptoc 
.IR icon-file ...
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Bitmaptoc
converts a file in \fIbitmap(5)\fP format into a \fBBITMAP struct\fP in
C code.  It recognizes old and new bitmap file formats.  This \fBBITMAP
struct\fP can be used like every other bitmap, e.g.  one which got read
from a file using \fBbitmapread\fP.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
\fImgr(1)\fP, \fIfonttoc(1)\fP, \fIbitmap(5)\fP
.\"}}}  
.\"{{{  author
.SH AUTHOR
Stephen A. Uhler, Michael Haardt
.\"}}}  
