.\"{{{}}}
.\"{{{  title
.TH browse 1 "August 15, 1992"
.\"}}}  
.\"{{{  name
.SH NAME
browse \(em an icon browser for MGR
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B browse
.RB [ \-r ]
\fBfilename\fP...
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Browse
displays the icon files specified on the command line in the current
window.  If all of the icons specified won't fit in the window, the
pop-up menu accessed from the middle mouse button permits paging back
and forth among the icons.
.LP
The Right or
.I pointing
button of the mouse, when clicked over an 
.I icon,
highlights the icon and prints its filename.
.\"}}}  
.\"{{{  options
.SH OPTIONS
.IP \fB\-r\fP
display the bitmaps with reverse colour.
.\"}}}  
.\"{{{  bugs
.SH BUGS
.TP 
*
The icon files are read from the same host
.I MGR
is executing on, not the host 
.I browse is running on.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
zoom(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
