'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: cut.1,v 1.1 88/07/08 13:37:10 sau Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/cut.1,v $
.TH cut 1L "January 30, 1988"
.SH NAME
cut \- cut text from a
.I MGR
window and send it to a program.
.SH SYNOPSIS
.B cut 
[ \fB-s\fP ]
[ \fBcommand\fP ]
.SH DESCRIPTION
Cut watches the global 
.I MGR
cut buffer and when activated, reads the buffer and starts
.B <command>
with the contents of the buffer as
.B <command>'s
standard input.
.LP
Initially,
.I cut
prompts the user for a spot on the display, moves there and becomes
a closed file cabinet icon.
Any time text is cut to to
.I MGR 's
global buffer, 
.I cut
highlights the file cabinet to indicate it has seen the cut text.
.I Cut
prepends the current date, time and message size to the text sent to 
.B <command>.
.LP
If 
.B \-s
is specified, 
.B cut
does not prompt the user for a spot, but uses the window as is.
This is useful for starting cut from the 
.I MGR
startup file.
If no
.B command
is given, 
.B cut 
looks for the command in the environment variable
.B CUT .
.SH BUGS
.SH SEE ALSO
mgr(1L)
snap(1L)
.SH AUTHOR
S. A. Uhler
