'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: iconmsgs.1,v 4.1 88/06/21 13:51:38 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/iconmsgs.1,v $
.TH iconmsgs 1L "July 30, 1986"
.SH NAME
iconmsgs \- message arrival notification
.SH SYNOPSIS
.B iconmsgs
[ \fB\-s\fP ]
[ \fB\-x\fP<pos> ]
[ \fB\-y\fP<pos> ]
[ \fB\-f\fP<font> ]
[ \fB\-p\fP<poll> ]
.SH DESCRIPTION
.I iconmsgs
looks for, and announces the arrival of new
.B msgs.
When initially invoked,
.I iconmsgs
shrinks its window to a bulletin board icon,
displaying the number of pending messages as notes tacked to the board.
When new messages arrive,
.B iconmsgs
rings the bell, and tacks a new message to the bulletin board.
If the 
.I iconmsgs
window is activated when messages are pending,
usually by clicking on it with the mouse,
iconmsgs creates a larger window with 
.I msgs
running in it.
.LP
While in the 
.I msgs
window, the middle mouse button activates a menu of commonly
used msgs commands.
.LP
.B iconmsgs
recognizes the following command line flags:
.TP 
-s
Don't reshape the window upon 
.B iconmsgs
invocation.
.TP 
-x<pos>
Starting x-coordinate of 
.I msgs
window.
.TP 
-y<pos>
Starting y-coordinate of 
.I msgs
window.
.TP 
-f<font_number>
Font to use for
.I msgs
window.
.TP 
-p<poll interval>
Look for new messages every
.I poll interval
seconds (defaults to 60).
.SH BUGS
Destroying the 
.I msgs
window while
.I msgs
is running is a bad thing to do.
.SH FILES
.TP 
.B /usr/spool/msgs/bounds
.TP 
.B $HOME/.msgsrc
.SH SEE ALSO
msgs(1)
mgr(1L)
mgrmsgs(1L)
.SH AUTHOR
S. A. Uhler
