.\"{{{  title
.TH MCLOCK 1
.\"}}}  
.\"{{{  name
.SH NAME
mclock \(em micky mouse clock
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B mclock
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Mclock
is a nice micky mouse clock.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
