.\"{{{  title
.TH MGRBIFF 1
.\"}}}  
.\"{{{  name
.SH NAME
mgrbiff \(em watch mailbox
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B mgrbiff
.RI [ mailbox ]
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Mgrbiff
watches your \fImailbox\fP and show if there is mail in it.
.\"}}}  
.\"{{{  files
.SH FILES
/usr/spool/mail/login \(em default mailbox
.\"}}}  
.\"{{{  bugs
.SH BUGS
Although the program is named biff, it does neither bark nor bite
the postman.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
Michael Haardt
.\"}}}  
