.\"{{{}}}
.\"{{{  title
.TH MGRVIEW 1 "October 11, 1992"
.\"}}}
.\"{{{  name
.SH NAME
mgrview \(em view MGR bitmap images
.\"}}}
.\"{{{  synopsis
.SH SYNOPSIS
.ad l
\fBmgrview\fP [ \fB\-r\fP \fIfile\fP | \fB\-l\fP \fIfile\fP ]
.ad b
.\"}}}
.\"{{{  description
.SH DESCRIPTION
\fBMgrview\fP reads a MGR bitmap (or standard input if none given) and displays it.
The right mouse button is used to move the displayed area, if the image
is too small for the window.  If pressed inside the window, it moves the
displayed area in the specified direction (viewed from the middle), if
it is pressed outside, the displayed area will be moved to the margin of
the image.  The middle button brings up a menu.
.\"}}}
.\"{{{  options
.SH OPTIONS
.IP "\fB\-r\fP \fIfile\fP"
Read bitmap from the (remote) server filesystem, which usually is faster than:
.IP "\fB\-l\fP \fIfile\fP"
reading bitmap from (local) client filesystem.
.\"}}}
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}
.\"{{{  author
.SH AUTHOR
Michael Haardt
.\"}}}
