.TH snap 1L "October 30, 1987"
.SH NAME
snap \- capture a portion of the display as a bitmap image
.SH SYNOPSIS
snap
[ \fB\-n\fP ]
\fB<file>\fP
.SH DESCRIPTION
.B Snap
lets a user capture a bit image of an arbitrary rectangular portion of
the display.
This image may be saved in a file, send to a printer, or copied back to
the display.
.PP
When 
.B snap
is active,
the user may sweep out an image with the 3rd mouse button.
Upon releasing the button, this image is captured and remembered
by
.B Snap.
The middle button pops-up a menu with the following options:
.TP 3
.B Print
The image snapped is sent to the printer (via 
.I lpr
) in 
.I MGR bitmap format
with the
.B \-v
flag set.
If the
.B PRINTER
environment variable is set, it is used to specify the printer name,
otherwise the image is sent to
.B lp .
.TP 3
.B File
The last image snapped is saved in the file specified on the command line
when
.B snap
was invoked, in
.I MGR bitmap format.
Successive invocations of
.B file
overwrite any previously stored images.
.TP 3
.B Review
Once
.B Review
is selected,
The user may sweep out (using the 3rd mouse button, as before)
an area on which to display the snapped image.
If nothing is swept within 10 seconds, 
.B snap
flashes, rings the bell, and reverts to capture mode.
While reviewing in enabled, the
.I snap 
icon remains inverse video.
The displayed image is clipped to fit within the region
swept out by the user.
If the user simply clicks the 3rd mouse button twice
without sweeping,
.B snap
copies the entire saved image to the display, starting at the mouse location.
.TP 3
.B Quit
.B Snap
de-iconifies itself and quits.
.LP
When 
.B \-n
is specified on the command line, the new (8 byte header) style bitmap
format is produced, instead of the old (6 byte header) format.
.SH FILES
.B /dev/bwtwo0
	to find the display image.
.SH SEE ALSO
lpr(1)
window_print(1L)
.SH DIAGNOSTICS
.TP 3
*
Can't find screen	
.I The frame buffer won't open.
.TP 3
*
Can't open file
.I
The file can't be opened for writing.
.SH BUGS
.TP 3
*
The user interface is overly simplistic.
.TP 3
*
.B snap
only works on the 
.I mgr
host.
.TP 3
*
The 
.B review
function can write on the display arbitrarily,
destroying its integrity.
.SH AUTHOR
S. A. Uhler
