.\"{{{}}}
.\"{{{  title
.TH WALK 1
.\"}}}  
.\"{{{  name
.SH NAME
walk \(em demo of a walking eye
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B walk
.RB [ \-d
.IR delay ]
.RB [ \-s ]
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
\fBWalk\fP lets an cute eye walk in your window.
.\"}}}  
.\"{{{  files
.SH FILES
(iconpath)/eye/* \(em eye icons
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
