'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: window_print.1,v 4.1 88/06/21 13:56:25 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/window_print.1,v $
.TH window_print 1L "July 3 1986"
.SH NAME
window_print \- print an image of an
.B
MGR
window on a printer.
.SH SYNOPSIS
.B
window_print
[ -\fBf \fPfilter ]
[ -\fBj \fPname ]
[ -\fBm \fPmessage ]
[ -\fBp \fPprinter ]
[ -\fBo \fPoption ]
[ -\fBx \fPfile ]
.SH DESCRIPTION
.B
Window print
prints the images of windows on a printer.
When first invoked,
.B
Window print
iconifies itself with the message 
.I Window dump.
A hard copy of a window is made by activating the
window print window and clicking
the third mouse button over the desired window.
.B Window_print
copies the image of the window onto a file, then invokes lpr
to print it.
.LP
command options
.TP 3
.B
-f filter
The name of an (optional) unix filter for converting the mgr bitmap format
file into a form suitable for 
.B
lpr.
.TP 3
.B
-[jJ] name
The name printed on the burst page of the printer, normally
.B
window.
.TP 3
.B
-m message
The string displayed in the iconified window.
.TP 3
.B
-[pP] printer
The name of the printer, as in
.B lpr.
.TP 3
.B
-v option
Normally lpr is invoked with the
.B -v
flag.
If
.B
option
is specified, it is used instead.
.TP 3
.B
-x file
The image files is copied to 
.B file
instead of being sent to 
.B lpr
.SH FILES
/tmp/pr*		temporary bit image file
.SH SEE ALSO
lpr(1)
.SH DIAGNOSTICS
debugging output may be obtained by setting the environment variable
.B
DEBUG.
.SH BUGS
The temporary file is created on the machine which is running mgr,
not the machine running
.B
window_print.
