'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: zoom.1,v 4.1 88/06/21 13:56:26 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/zoom.1,v $
.TH zoom 1L "June 10, 1986"
.SH NAME
zoom \- an icon editor for
.I mgr
.SH SYNOPSIS
.B zoom
<\fBicon file\fP> ...
.SH DESCRIPTION
.B zoom
is a mouse driven icon editter for
.I mgr.
.B Zoom
divides the window into three regions, a banner line at the top containing
four status fields,
a message line at the bottom,
and the remainder of the window for an enlarged, or
.I zoomed
representation of
.I <icon>
being editted.
If the first file given on the command line is not an icon,
zoom prompts for its width and height.
.LP
The current state of zoom is indicated by the four status fields in the
banner line.
.TP
*
The first, or
.I raster function
field displays the current raster-op function to be applied to the next
edit operation.  This function may be changed with the pop-up menu,
activated by pressing the middle mouse button while the mouse track is in the 
.I raster function
field.
Normally the choices are 
.B set, clear, toggle
and
.B grid.
The first three are raster-op functions; the
.I grid
option toggles the bitmap alignment grid.
If the
.B put
command is pending (see below), the raster-op choices become
.B copy, paint mask,
and
.B exclusive-or. 
.TP
*
The second, or
.I edit
field displays one of the six possible edit functions:
.B Yank, Put, Shrink, Grow, Fix,
and
.B  Undo.
Fix and Undo are performed when selected. 
.B Fix
changes the window size
to give square pixels. 
.B Undo
un-does the previous edit operation.
If any of the other functions is selected, it becomes the pending function,
and is highlighted.
When a function is pending, the next sweep operation performs that function
on the group of pixels enclosed by the sweeping rectangle (the 
.I selected
pixels).
.RS
.TP
.B Yank
copies the 
.I selected
pixels into the yank buffer.
.TP
.B Put
combines the yank buffer with the 
.I selected
pixels in a manner determined
by the current
.I raster function
field.
.TP
.B Shrink
makes the icon smaller by scaling the selected pixels to fill the entire
window.
.TP 
.B Grow
makes the icon bigger by scaling the entire icon to fit into the
selected pixel region.
.RE
.TP 
*
The Third or
.I size
field displays the current 
.I width
and
.I height
of the icon, in pixels.
The size of the icon may be changed by selecting the pop-up menu
when the mouse track is in the
.I size
field
and responding to the prompt.
While in the prompt window, the menu permits the selection
of several standard icon sizes.
.TP
*
The fourth, and final field is the
.I file
field.
The
.I file
field displays the current file name of the icon.
The filing options
.B Save, Get, Yank,
and
Quit
are, as usual, accessed by a pop-up menu when the mouse track
is in the
.I file
field.
The
.I file
options prompt for a file name.  
A list of all of the files specified on the command line
is available via the pop-up menu within the prompt window.
.RS
.TP
.B
Save
saves the icon by the specified name.
.TP
.B Get
edits a new icon , tossing the current icon into the bit-bucket.
.TP
.B Yank
copies the specified icon into the
.I yank 
buffer for use with the
.B put
command.
.TP
.B Quit
quits
Zoom. Quit does
.B NOT
save the icon.  A save must be explicitly issued first.
Zoom may also be terminated by typing
"Q\er" to the window, or hitting your favorite interrupt key.
.RE
.LP
For those who are not particularly fond of rodents, all of the
.B zoom 
commands may be accessed via 1 or 2 letter keyboard commands
(followed by a \en), some of which
are:

 	R	Repaint window
 	x	toggle alignment grid
 	w	FIX window aspect ratio
 	u	UNDO

 	s1	select SET mode
 	s2	select CLEAR mode
 	s3	select TOGGLE mode

 	f	SAVE file
 	g	GET a new file
 	y	YANK a file
 	Q	QUIT

 	F1	select YANK function
 	F2	select PUT function
 	F3	SHRINK icon
 	F4	GROW icon

 	P0	set COPY mode
 	P1	set PAINT mode
 	P2	set MASK mode
 	P3	set XOR mode

.LP
Okay, now to edit the icon.
.TP 
*
Pressing the middle button and moving it either sets or clears the pixels
it passes over.  If the first pixel it touches is clear, the pixels will
be set; if it is set, all touched pixels will be cleared.
.TP
*
Holding, moving, then releasing the right mouse button sweeps out
a rectangular region of
.I selected pixels.
If no function is currently highlighted in the 
.I edit
field,
the current raster-op function is performed on 
the selected pixels.
Otherwise, the highlighted function is performed.
.SH BUGS
.TP 3
*
Zoom works best on small icons, running on the local machine.
.TP 3
*
You can't view the actual size of the icon being editted.
.TP 3
*
Icon coordinates must be typed in exactly in the form of
.B x
,
.B y
with no spaces or tabs.
.SH SEE ALSO
browse(1L)
dump(5L)
mgr(1L)
