.TH mmgetfilenm 1 ""
.SH NAME
/usr/local/lib/mm/mmgetfilename - Ask the user to name a file in a given format
.br
/usr/local/lib/mm/mmgetchar - read one char
.SH SYNOPSIS
.HP
\fB/usr/local/lib/mm/mmgetfilename\ \fIformat-name file-name\fR
.HP
\fB x=`/usr/local/lib/mm/mmgetchar`\fR
.SH DESCRIPTION
The
.I mmgetfilename
program will ask the user for the name of a file in the specified format, 
and will copy that file to the file-name given as the second argument.
.P
If this doesn't sound very useful by itself, you're right.  However, this 
turns out to be all you need in order to add some useful functionality to 
mailcap-oriented programs such as mailto(1).  For example, the following line 
in a mailcap file allows mailto to help the user include PostScript in 
outgoing mail:
.nf
    application/postscript ; \\
	lpr -Pipa %s ; \\
	label="Include a Postscript File";\\
	compose="getfilename Postscript %s"
.fi
.P
The
.I mmgetchar 
simply reads one character in and echo's it to stdout.
.P
This is implemented as a script so that it can be customized
by the system administrators.
.SH SEE ALSO
.SH BUGS
Unfortunately it seems impossible to have a portable version of for
single char reads
that can simply be embedded into a script. We're still trying though.
.SH COPYRIGHT
.SH AUTHOR
Stuart Lynne
.br
Adapted from getfilename(1) by Nathaniel S. Borenstein, Bellcore
