.TH mmsavefile 1 ""
.SH NAME
mmsavefile - a script for processing files received in a MIME message 
.SH SYNOPSIS
.HP
\fB/usr/local/mm/mmsavefile type file\fR
[\fIname\fR]
..
..
.SH DESCRIPTION
.P
The
.I mmsavefile
program will allow you to save a file from a metamail message.
It presents a short menu with options to save or forward
the message.
.P
.SH MAILCAP
To use these programs with 
.I metamail 
add the following line to your 
.B mailcap
file.
.nf
        image/x-file; \\
                /usr/local/mm/mmsavefile %t %s ${name} ; \\
                compose=/usr/local/mm/mmgetfilenm %t %s; \\
                edit=/usr/local/mm/mmgetfilenm %t %s; \\
                label="A File"; \\
                needsterminal
.fi
.P
The MIME content type being used is
.B image/x-file.
.SH SEE ALSO
mmgetfilenm(1), mailto(1), metamail(1), mmsend(1)
.SH BUGS
.SH COPYRIGHT
.SH AUTHOR
Stuart Lynne
