.TH mmshowpart ""
.SH NAME
mmshowpart - Fetch and display the body of a mail message that is included by reference
.SH SYNOPSIS
.HP
\fB/usr/local/mm/mmshowpart\ \fIfile id partnum totalnum\fR
.HP
.SH DESCRIPTION
The
.I mmshowpart
program will squirrel away the body of a MIME-format message that is of type 
"message/partial" for later use.  When it is called on the last piece, it 
will put the pieces together and call metamail to display the full message.  
It is intended to be called by metamail via a mailcap entry like the following
in 
.I /usr/local/lib/mm/forward.mailcap:
.nf
        message/partial; \
	    /usr/local/mm/mmsavepart %s %{id} %{number} %{total}
.fi
.SH SEE ALSO
filter(1), metamail(1), mmforward(1), splitmail(1)
.SH BUGS
.SH COPYRIGHT
.SH AUTHOR
Stuart Lynne
.SH SEE ALSO
metamail(1), mmforward(1)
.SH BUGS
The parts are squirrelled away on /tmp, which means that /tmp can fill up 
if you never get the remaining parts.  When the message is finally displayed, 
via metamail, the parts are all discarded, which might also be seen as a bug 
by some...
.SH COPYRIGHT
.SH AUTHOR
Stuart Lynne 
.br
Adapated from showpart(1) by Nathaniel S. Borenstein, Bellcore
