.TH mmshowfax 1 ""
.SH NAME
mmshowfax - a script for processing faxes received in a MIME message 
..
.SH SYNOPSIS
.HP
\fB/usr/local/lib/mm/mmshowfax -ok\fR
.\".HP
.\"\fBmmprintfax type file\fR
.\"[
.\".I name
.\"]
..
.SH DESCRIPTION
The
.I mmshowfax
program will attempt to display a fax file on your terminal.
It presents a short menu with options to view, save or forward
the message.
.P
.P
Called with 
.I -ok
the 
.I mmshowfax
program will return an error if the terminal you are on cannot display
a fax.
..
.\".P
.\"The
.\".I mmprintfax
.\"program will format the fax for printing on the default system printer.
..
.SH MAILCAP
To use these programs with 
.I metamail 
add the following line to your 
.B mailcap
file.
.nf
        image/x-fax-tiff-f; \\
                /usr/local/mm/mmshowfax %t %s ${name} ; \\
                test=/usr/local/mm/mmshowfax -ok %t %s ${name} ; \\
                compose=/usr/local/mm/mmgetfilenm %t %s; \\
                edit=/usr/local/mm/mmgetfilenm %t %s; \\
                print=/usr/local/mm/mmprintfax %t %s ${name}; \\
                label="A FAX - TIFF/F File"; \\
                needsterminal
.fi
.P
The MIME content type being used is
.B image/x-fax-tiff-f.
.SH SEE ALSO
mmgetfilenm(1), mailto(1), metamail(1), mmsend(1)
.SH BUGS
.SH COPYRIGHT
.SH AUTHOR
Stuart Lynne
