#!/bin/csh -f

######################################################################
#
# Copyright (C) 1988, 1989  Steven B. Byrne.
# All rights reserved.
#
######################################################################

set testSuite = (class blocks array strings chars intmath floatmath)

foreach test ($testSuite)
    echo "Testing ${test}..."
    ../mst -r ${test}.st >& ${test}.log
    diff ${test}.base ${test}.log
end
