			$1 == "__dn_skipname" || \
			$1 == "__fp_query" || \
			$1 == "__hostalias" || \
			$1 == "__p_class" || \
			$1 == "__p_time" || \
			$1 == "__p_type" || \
			$1 == "__putlong" || \
			$1 == "__putshort" || \
			$1 == "_checkhost" || \
			$1 == "_endhtent" || \
			$1 == "_gethtbyaddr" || \
			$1 == "_gethtbyname" || \
			$1 == "_gethtent" || \
			$1 == "_getlong" || \
			$1 == "_getshort" || \
			$1 == "_res_close" || \
			$1 == "_sethtent" || \
			$1 == "_validuser" || \
			$1 == "bindresvport" || \
			$1 == "dn_comp" || \
			$1 == "dn_expand" || \
			$1 == "endhostent" || \
			$1 == "endnetent" || \
			$1 == "endprotoent" || \
			$1 == "endservent" || \
			$1 == "gethostbyaddr" || \
			$1 == "gethostbyname" || \
			$1 == "getnetbyaddr" || \
			$1 == "getnetbyname" || \
			$1 == "getnetent" || \
			$1 == "getprotobyname" || \
			$1 == "getprotobynumber" || \
			$1 == "getprotoent" || \
			$1 == "getservbyname" || \
			$1 == "getservbyport" || \
			$1 == "getservent" || \
			$1 == "herror" || \
			$1 == "inet_addr" || \
			$1 == "inet_lnaof" || \
			$1 == "inet_makeaddr" || \
			$1 == "inet_netof" || \
			$1 == "inet_network" || \
			$1 == "inet_ntoa" || \
			$1 == "p_cdname" || \
			$1 == "p_query" || \
			$1 == "p_rr" || \
			$1 == "rcmd" || \
			$1 == "res_init" || \
			$1 == "res_mkquery" || \
			$1 == "res_query" || \
			$1 == "res_querydomain" || \
			$1 == "res_search" || \
			$1 == "res_send" || \
			$1 == "rexec" || \
			$1 == "rresvport" || \
			$1 == "ruserok" || \
			$1 == "ruserpass" || \
			$1 == "sethostent" || \
			$1 == "sethostfile" || \
			$1 == "setnetent" || \
			$1 == "setprotoent" || \
			$1 == "setservent" || \
