'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: bounce.1,v 4.1 88/06/21 13:51:18 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/bounce.1,v $
.TH bounce 1L "April 30, 1985"
.SH NAME
bounce \- A standard graphics demo
.SH SYNOPSIS
.B bounce
[ \fB\-s\fP ]
.SH DESCRIPTION
.B Bounce
bounces 10 lines around the window forever.
The
.B \-s
flag bounces the lines slower.
Bounce stops if its window is obscured.
.SH SEE ALSO
mgr(1L)
.SH AUTHOR
D. Nachbar
