.\"                        Copyright (c) 1988 Bellcore
.\"                            All Rights Reserved
.\"       Permission is granted to copy or use this program, EXCEPT that it
.\"       may not be sold for profit, the copyright notice must be reproduced
.\"       on copies, and credit should be given to Bellcore where it is due.
.\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
.\"
.TH clock2 1L "April 30, 1985"
.SH NAME
clock2 \- Analog display of time of day on a 
.I mgr
terminal.
.SH SYNOPSIS
.B clock2
.SH DESCRIPTION
.B Clock2
draws an analog clock face that fills the current window, on which
it shows the current time of day.
Square-ish windows produce the best results.
.SH "SEE ALSO"
clock(1), mgr(1)
.SH AUTHOR
S. A. Uhler
