.\"                        Copyright (c) 1988 Bellcore
.\"                            All Rights Reserved
.\"       Permission is granted to copy or use this program, EXCEPT that it
.\"       may not be sold for profit, the copyright notice must be reproduced
.\"       on copies, and credit should be given to Bellcore where it is due.
.\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
.\"
.TH CLOCK 1 "April 30, 1985"
.SH NAME
clock \- Digital display of time of day on a 
.I mgr
terminal.
.SH SYNOPSIS
.B clock
[ \fB\-b\fP ]
[ \fB\-f\fP<font> ]
[ \fB\-s\fP ]
.SH DESCRIPTION
.B Clock
displays a time of day clock on a 
.I mgr
window.
The window shrinks to just enclose the display.
The
.B -f
flag is used to specify the font to use
for the display.
.B clock -f5
is typical.
.B -b
pushes the clock to the bottom of the display, and
.B -s
doesn't reshape the window.
.SH "SEE ALSO"
clock2(1), mgr(1)
.SH AUTHOR
S. A. Uhler
