'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: close.1,v 4.1 88/06/21 13:51:28 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/close.1,v $
.TH close 1L "May 20, 1988"
.SH NAME
close \- Close a 
.I mgr
window.
.SH SYNOPSIS
.B close
[ \fImessage\fP
[ \fIfont-number\fP ] ]
.SH DESCRIPTION
.B Close
Makes the current window very small, displays
.I message
in it, and moves it to an unoccupied spot on the screen.
If the message includes "\c
.BR %d ""","
then the window set ID will replace it when the message is displayed.
Upon reactivation, the window returns to its former size and position.
If the 
.I closed
window is ever covered, it attempts to find and move itself to
some other unoccupied spot.
.PP
If no
.I message
is given
or the message is of zero length,
the current 
.I hostname
along with the parenthesized
.I "window ID"
is displayed.
The window ID can be used to activate the window from the keyboard.
.BR Left -\c
.I windowID
or
.BI Right -\c
.I windowID
will activate the window if the window ID is a single digit.
.BR Left - w -\c
.I windowID
or
.BR Right - w -\c
.I windowID
will activate the window for any window ID.
Window ID
.B 0
is an alias for window ID
.BR 10 .
.PP
An optional second argument,
.IR fontnumber ,
may be specified to indicate the font in which
.I message 
is displayed.
.SH EXAMPLES
.ft B
.nf
.in +10
close
close 'source directory'
close '' 0
close 'source directory' 7
.fi
.in
.ft R
.SH BUGS
.TP 3
*
Not all windows on the screen may be closed at once.
.SH SEE ALSO
mgr(1L)
.SH AUTHORS
S. A. Uhler
.br
M. H. Bianchi
