.TH dmgr 1L "December 12, 1987"
.SH NAME
Dmgr \- A rudimentary troff previewer for mgr
.SH SYNOPSIS
ditroff 
[ \fI<ditroff args>\fP ] ... \(br
.B Dmgr
.SH DESCRIPTION
.B Dmgr
is a simple 
.I troff
previewer for 
.I MGR .
It reads
.I ditroff
output
and places characters on an
.I MGR
window in their proper relative location on
the page, using whatever 
.I MGR
character font happens to be current.
Bold face is indicated by overstiking, italics by underlining.
.B Dmgr
pauses at the end of every page and rings the bell.
A 
.I RETURN
causes 
.B dmgr
to continue with the next page.
.SH BUGS
.TP 3
*
.B Dmgr
uses the current 
.I Mgr
font for output, which is probably never the appropriate font to use.
As such 
.B Dmgr
is useful for previewing the page layout; not for actually reading the 
document.
.TP 3
*
.B Dmgr
doesn't know about special characters or ligatures,
which are printed as dashes "-".
.TP 3
*
.B Dmgr
invents a page size, suitable for 8-\(12 by 11 inch printers
instead of extracting it from 
.I ditroff
output.
.SH SEE ALSO
mgr(1L) ditroff(1)
.SH AUTHOR
S. A. Uhler
