'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: lock.1,v 1.1 88/07/20 11:12:25 sau Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/lock.1,v $
.TH lock local
.SH NAME
lock \- lock the sun console
.SH SYNOPSIS
lock
.SH DESCRIPTION
.B lock
displays a screen-phosphor saving pattern on the sun console.  When
you login password is typed on standard input, the screen is restored.
If you mistype your password, the pattern direction reverses, and
you may try again.
.SH FILES
.TP *
/dev/bwtwo0	to find the screen
.TP *
/etc/passwd	to check the login password
.SH SEE ALSO
lockscreen(1)
.SH BUGS
Error checking is poor
.SH AUTHOR
S. A. Uhler
