'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: maze.1,v 4.1 88/06/21 13:51:41 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/maze.1,v $
.TH maze 1L "March 30, 1986"
.SH NAME
Maze \-  A graphical game of solitare
.SH SYNOPSIS
.B maze
.SH DESCRIPTION
.B Maze
draws a maze and permits you to navigate around it while displaying both a top and
perspective view. 
The
.B f
(or
.B space
),
.B r,
.B l,
and
.B b
keys move you
forward, right, left, and
backwards respectively.
You can sometimes see others in the maze if they are playing
.B maze
somewhere else on the network.
.SH BUGS
.TP 3
*
This is truly a mindless endeavor.
.TP 3
*
When other maze players die, they leave ghosts in the maze.
.SH SEE ALSO
mgr(1L)
.SH ACKNOWLEDGEMENTS
This program was written by 
.I "J. Gosling"
for
.I Andrew
and ported to
.B mgr.
