.\"{{{  title
.TH MGRMODE 1
.\"}}}  
.\"{{{  name
.SH NAME
mgrmode \(em set or clear MGR window modes
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B mgrmode 
.RB [ setmode | clearmode ] 
.I mgr-modes 
.R \&...
.br
.B mgrmode 
.B clearall
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Mgrmode
sets or clears MGR window modes for the current window.
.B setmode
(default) sets the mode,
.B clearmode
clears the mode and 
.B clearall clears all modes, except \fBactive\fP.
.\"}}}  
.\"{{{  options
.SH OPTIONS
.IP \fBM_ABS\fP
Turn on Absolute Coordinate mode.
.IP \fBM_ACTIVATE\fP
Activate window (not really a mode).
.IP \fBM_AUTOEXPOSE\fP
Expose window when written to.
.IP \fBM_BACKGROUND\fP
Do not block window update when window is obscured.
.IP \fBM_DUPKEY\fP
Duplicate the Escape character when from keyboard.
.IP \fBM_NOBUCKEY\fP
Turn off mgr interpreting Left and Right (Buckey) keys;
Pass them on to the application.
.IP \fBM_NOINPUT\fP
Keyboard input is held until cleared or another window
becomes active.
.IP \fBM_NOWRAP\fP
Do not wrap around when text reaches right edge of window.
.IP \fBM_OVERSTRIKE\fP
Turn on overstriking of text.
.IP \fBM_SNARFHARD\fP
Snarf (cut) even if there are errors.
.IP \fBM_SNARFLINES\fP
Only cut entire lines.
.IP \fBM_SNARFTABS\fP
Change spaces to tabs within the snarf buffer.
.IP \fBM_STACK\fP
Turn on event stacking.
.IP \fBM_STANDOUT\fP
Write characters in standout mode (foreground and background
colors reversed).
.IP \fBM_WOB\fP
White On Black, entire window's sense of white and black is
reversed.
.PP
\fBM_\fP may be omitted.  Lower case letters are permitted.  \fBM_ABS\fP = \fBABS\fP = \fBabs\fP.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
