'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: mgrmail.1,v 4.1 88/06/21 13:51:52 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/mgrmail.1,v $
.TH mgrmail 1L "April 30, 1985"
.SH NAME
mgrmail -\ Notification of mail arrival
.SH SYNOPSIS
.B mgrmail
[ \fB\-s\fP ]
[ \fB\-x\fP<pos> ]
[ \fB\-y\fP<pos> ]
[ \fB\-f\fP<font> ]
[ \fB\-p\fP<poll> ]
[ \fB\-M\fP<mailer> ]
.SH DESCRIPTION
.I Mgrmail
looks for, and announces the arrival of new mail.
When initially invoked,
.I mgrmail
shrinks its window to the single line
.B Looking for new mail.
When new mail arrives,
.I mgrmail
rings the bell, and states
.I You have new mail.
If the 
.I mgrmail
window is activated, usually by clicking on it with the mouse,
It creates a larger window with 
.I readmail
running in it.
.LP
While in the 
.I readmail
window, the middle mouse button activates a menu of commonly
used mail commands.
.LP
.B Mgrmail
recognizes the following command line flags:
.TP 
-s
Don't reshape the window upon 
.B mgrmail
invocation.
.TP 
-x<pos>
Starting x-coordinate of 
.I readmail
window.
.TP 
-y<pos>
Starting y-coordinate of 
.I readmail
window.
.TP 
-f<font_number>
Font to use for
.I readmail
window.
.TP 
-p<poll interval>
Look for new mail every
.I poll interval
seconds (defaults to 60).
.TP 
-M<mailer>
Use
.I mailer
to read mail, instead of
.I mail.
.SH BUGS
The 
.I readmail
window sleeps for a second at its termination to permit
.I mail
to indicate new mail arrival while reading mail.
.LP
Destroying the 
.I mail
subwindow
is a bad thing to do.
.SH FILES
.TP 
.B /usr/spool/mail/$USER
.SH SEE ALSO
mail(1)
mgr(1L)
.SH AUTHOR
S. A. Uhler
