'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: mgrmsgs.1,v 4.1 88/06/21 13:51:54 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/mgrmsgs.1,v $
.TH mgrmsgs 1L "April 30, 1985"
.SH NAME
mgrmsgs \- message arrival notification
.SH SYNOPSIS
.B mgrmsgs
[ \fB\-s\fP ]
[ \fB\-x\fP<pos> ]
[ \fB\-y\fP<pos> ]
[ \fB\-f\fP<font> ]
[ \fB\-p\fP<poll> ]
.SH DESCRIPTION
.I Mgrmsgs
looks for, and announces the arrival of new
.B msgs.
When initially invoked,
.I mgrmsgs
shrinks its window to the single line
displaying the number of pending messages.
When new messages arrive,
.B mgrmsgs
rings the bell, and updates the current message count.
If the 
.I mgrmsgs
window is activated when messages are pending,
usually by clicking on it with the mouse,
It changes to a larger window with 
.I msgs
running in it.
.LP
While in the 
.I msgs
window, the middle mouse button activates a menu of commonly
used msgs commands.
.LP
.B Mgrmsgs
recognizes the following command line flags:
.TP 
-s
Don't reshape the window upon 
.B mgrmsgs
invocation.
.TP 
-x<pos>
Starting x-coordinate of 
.I msgs
window.
.TP 
-y<pos>
Starting y-coordinate of 
.I msgs
window.
.TP 
-f<font_number>
Font to use for
.I msgs
window.
.TP 
-p<poll interval>
Look for new messages every
.I poll interval
seconds (defaults to 60).
.SH FILES
.TP 
.B /usr/spool/msgs/bounds
.TP 
.B $HOME/.msgsrc
.SH SEE ALSO
msgs(1)
mgr(1L)
.SH AUTHOR
S. A. Uhler
