'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: oclose.1,v 4.1 88/06/21 13:51:56 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/oclose.1,v $
.TH oclose 1L "April 30, 1985"
.SH NAME
oclose \- Close a 
.I mgr
window.
.SH SYNOPSIS
.B oclose
[ \fB<message>\fP ]
[ \fB-F\fPn ]
.SH DESCRIPTION
.B Oclose
Makes the current window very small, displays
.I message
in it, and moves it to the bottom of the screen.
Upon reactivating the window, it returns to its former size and position.
If no
.I message
is given,
the current 
.I hostname
is displayed instead.
An optional font number may be specified to indicate
the font in which
.I message 
is displayed.
.SH BUGS
.TP 3
*
.I oclose
does a poor job of placing the icon.
.TP 3
*
Not all windows on the screen may be closed at once.
.SH SEE ALSO
mgr(1L)
.SH AUTHOR
S. A. Uhler
