'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: rotate.1,v 4.1 88/06/21 13:52:01 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/rotate.1,v $
.TH rotate 1L "June 30, 1986"
.SH NAME
rotate \- Rotate a bitmap 90 degrees.
.SH SYNOPSIS
.B Rotate
[ \fB\-w wide \-h high\fP ]
[ \fB\-x\fP ]
[ \fB\-v\fP ]
.SH DESCRIPTION
.B Rotate
is a filter that rotates a 1 bit deep bitmap clockwise by 90 degrees.
Normally
.B rotate
expects a bitmap in 
.I mgr
format which uses a bitmap header to specify the width and height.
Alternately, the
.B -w
and
.B -h
flags may be used to indicate the bitmap 
.I width
and
.I height
if no bitmap header is present.
If 
.B -x
is specified, no bitmap header will be produced for the resultant
bitmap.
The 
.B -v
flags prints 
.B <'s
and
.B >'s
to help stave off boredom while
.B rotate
is running.
.SH BUGS
.B Rotate
can't currently rotate bitmaps with more than 1200 rows.
.SH SEE ALSO
bitmap(5L)
.SH AUTHOR
S. A. Uhler
