.TH set_console 1 "October 11, 1992"
.SH NAME
set_console \- redirect console messages to a tty
.SH SYNOPSIS
.B set_console
.SH DESCRIPTION
.B Set_console ,
when run in a tty redirects console messages to that tty.
.SH BUGS
Console messages automatically get reset to the console when \fIMGR\fP
is suspended.  Set_console should be reissued after resuming a suspended
.I MGR .
.SH AUTHOR
S. A. Uhler, Michael Haardt
