'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: set_termcap.1,v 4.1 88/06/21 13:52:03 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/set_termcap.1,v $
.TH Set_termcap 1L "April 30, 1985"
.SH NAME
set_termcap, set_emacs \- set an appropriate
.B TERMCAP
entry for
.B MGR.
.SH SYNOPSIS
eval `\fBset_termcap \fP[\fB -b \fP]`
.SH DESCRIPTION
.B Set_termcap
Prints on 
.I stdout
the
.I shell
commands required to set the
.B TERMCAP
environment variable appropriately for the current window size on a
.I mgr
terminal.
.I Set_termcap
looks at the
.B SHELL
environment variable to decide what shell commands are appropriate.
the command
.B eval `set_termcap`
sets the TERM and TERMCAP environment variables appropriately.
.LP
.I Set_emacs
optimizes the termcap entry for
.B GNU-emacs,
which knows how to 
deal with scrolling regions and multiple line inserts and deletes,
whereas
.I set_termcap
keeps 
.B vi
happy.
.SH BUGS
.B csh
usrs need to use:
.B set noglob; eval `set_termcap`
to keep the shell from getting confused.
.SH SEE ALSO
csh(1)
mgr(1L)
sh(1)
.SH AUTHOR
S. A. Uhler
