'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: show.1,v 4.1 88/06/21 13:52:07 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/show.1,v $
.TH show 1L "April 30, 1985"
.SH NAME
show \- displays a bit-mapped image on a
.I mgr
window.
.SH SYNOPSIS
.B show
[\fB\-r\fP]
[ \fB<x coord>\fP ]
[ \fB<y coord>\fP ]
[\fB<bits wide>\fP]
.SH DESCRIPTION
.B Show
copies its standard input, which is assumed to be in
.I MGR bitmap format
to the
window as a bit mapped image.
The starting position of the bit map relative to the top left
corner of the window may be given as
.I x coord
and
.I y coord
respectively.
If
.I bits wide
is specified on the command line,
.B show
assumes no bitmap header is present.
Specifying
.B \-r
changes the sense of black and white.
.LP
Bit maps too big to fit on the window are clipped.
The incoming data for each row should be rounded up to an
even number of bytes.  The bits are displayed left to right,
then top to bottom.
.SH BUGS
Large bit maps take too long to display.
.SH SEE ALSO
mgr(1L)
bitmap(5L)
