'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: startup.1,v 4.1 88/06/21 13:52:11 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/startup.1,v $
.TH startup 1L "April 30, 1985"
.SH NAME
startup \- produce a 
.B startup
file reflecting the current
.I mgr
screen layout.
.SH SYNOPSIS
.B startup
.SH DESCRIPTION
.B Startup
produces the current
.I mgr
window layout on its standard output,
in a form suitable for the 
.I mgr
startup file,
.B $HOME/.mgrc.
.SH BUGS
.I startup
produces only the windows positions, neglecting the fonts and commands
currently running in the windows.
.SH SEE ALSO
mgr(1L)
