'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: stringart.1,v 4.1 88/06/21 13:52:15 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/stringart.1,v $
.TH stringart 1L "April 30, 1985"
.SH NAME
stringart \- A standard graphics demo
.SH SYNOPSIS
.B stringart
.SH DESCRIPTION
.B Stringart
draws bunches of lines in a geometric patterns, erases them, and starts again
with a different pattern.
.SH SEE ALSO
mgr(1L)
