'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: tjfilter.1,v 4.1 88/06/21 13:52:17 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/tjfilter.1,v $
.TH tjfilter 1L "June 30, 1986"
.SH NAME
Tjfilter \- Bitmap 
.I lpr
filter for the
.B HP ThinkJet
printer.
.SH SYNOPSIS
.B tjfilter
[ \fB-r\fP ]
.SH DESCRIPTION
.B Tjfilter
reads its
.I standard input
which is expected to be a one bit deep
.I bitmap
image in
.B mgr
format and transforms it for printing on an
.B HP ThinkJet
printer.
If 
.B -r
is specified, the bitmap is reversed (ala a photographic negative).
For bitmaps which are wider than 640 dots, but less than 640 dots
high,
.B tjfilter
calls
.B rotate(1L)
in order to fit the bitmap on the printer.
.LP
.B Tjfilter
is normally used as the
.B vf
filter in the
.B HP ThinkJet
printcap entry: ...:vf=/usr/local/bin/tjfilter:...
.SH BUGS
The 
.B HP Thinkjet
printer can print a maximum of 640 dots per line.  
Bitmaps that don't fit get truncated.
.SH SEE ALSO
bitmap(5L)
rotate(1L)
lpr(1L)
