.TH MATCHES 1 local
.SH NAME
matches \- test if string2 is contained in string1
.SH SYNOPSIS
.B matches string1 string2
.SH DESCRIPTION
.I Matches
returns a 0 if string2 is contained in string1, otherwise it returns a 1.
.PP
.I Matches
is designed to be used by
.I Pcomm
in a shell script for automatically logging a user onto a remote system.
.PP
.SH EXAMPLE
.nf
	# read some input
	read junk
	# test to see the string matches 'login failed'
	matches $junk 'login failed'
	# test the exit code of the matches command
	if [ $? \-eq 0 ]
	then
		exit 1
	fi
.fi
.SH "SEE ALSO"
pcomm(1), waitfor(1), modem_break(1), Pcomm Reference Manual
