.TH MODEM_BREAK 1 local
.SH NAME
modem_break \- send a modem break
.SH SYNOPSIS
.B modem_break
.SH DESCRIPTION
.I Modem_break
creates a ``modem break'' on the stdout.  Modem break is a condition of
a communications line when the line is held ``low'' for 200 ms.  It is
typically used to tell the remote system to switch to a different
baud rate.
.PP
.I Modem_break
is designed to be used by
.I Pcomm
in a shell script for automatically logging a user onto a remote system.
.PP
.SH EXAMPLE
.nf
	while true
	do
		# wait 5 seconds for the login prompt
		waitfor \-5 login:
		# test the exit code of the waitfor command
		if [ $? \-eq 0 ]
		then
			# send my user ID and break out of the loop
			echo egray
			break
		fi
		# send a modem break
		modem_break
	done
.fi
.SH "SEE ALSO"
pcomm(1), waitfor(1), matches(1), Pcomm Reference Manual
