#  Makefile
#
#   (c) Copyright 1992 by David M. Siegel.
#       All rights reserved.
#
#  $Id$

include ../../include/conf.mk

LIBNAME = libutil.a

SRCS = alarm.c daemon.c dispatch.c file.c hash.c list.c net.c \
	pidlock.c reap.c show.c strcasecmp.c tcp.c tv.c

LIBNAME = util

include ../../make/lib.mk
