.TH ENSLAVE 1 "20 Jul 1991" "MandelSpawn 0.06"
.SH NAME
enslave \- start MandelSpawn computation servers
.SH SYNOPSIS  
.B enslave 
[
.B \-v
] [
.B \-n
] [ host ] ...
.SH DESCRIPTION  
.I Enslave
starts MandelSpawn computation
servers (see 
.IR mslaved (8))
on hosts listed in the file
\fI$HOME/.enslave\fP.  If a list of hostnames is given as 
arguments, then servers are started only on those hosts.
.PP
The \fB\-v\fP option causes \fIenslave\fP to print the rsh commands
it executes to start the servers.  With
the \fB\-n\fP option, the commands are printed but not executed.
.PP
.sh "THE .enslave FILE"
.PP
The file \fI.enslave\fP in the user's home directory contains the
information necessary to start the computation servers.  It contains
one line per host, each consisting of two or more whitespace-separated
fields: the host name, the directory where the binaries of \fImslaved\fP and
\fImslavedc\fP are stored, and any options that are to be passed to
\fImslavedc\fP.  The directory name may be relative to the user's home 
directory on the remote host and should end with a slash.
.PP
In addition to the \fI.enslave\fP file, \fIenslave\fP uses information
from the user's \fI.rhosts\fP file to determine a username for executing
commands on each of the remote hosts.  Additional hostname-username 
pairs for non-trusted hosts may be stored in \fI.rhosts\fP format in the 
file \fI.rhostile\fP.
.SH FILES
.ta 2i
$HOME/.enslave	control file
.br
$HOME/.rhosts	hostname-username pairs for trusted hosts
.br
$HOME/.rhostile	hostname-username pairs for non-trusted hosts
.PP
.SH "SEE ALSO"
xms(1), bms(1), mslaved(8), mslavedc(8)
.PP
.SH BUGS
Forking off one rsh per host in parallel may be considered anti-social
behaviour if the number of hosts is large. 
.PP
Hostname aliases are not taken into account, so hostnames must
be spelled identically in \fI.enslave\fP, \fI.mslaves\fP, \fI.rhosts\fP,
and \fI.rhostile\fP.
.SH COPYRIGHT
.if n Copyright (C) 1990 Andreas Gustafsson (gson@niksula.hut.fi)
.if t Copyright \(co 1990 Andreas Gustafsson (gson@niksula.hut.fi)

