.TH MSLAVEDC 8 "20 Jul 1991" "MandelSpawn 0.06"
.SH NAME 
mslavedc \- MandelSpawn computation server control program
.SH SYNOPSIS  
.B mslavedc \-k 
|
.B \-q 
host | [
.B \-p 
port ] [ 
.B -n 
niceval ] [
.B \-t 
timeout ] mslaved
.SH DESCRIPTION  
.I mslavedc
is a program for starting and killing \fImslaved\fP processes on
machines where this is not done automatically by 
.IR inetd (8C).
.I Mslavedc 
is used by the 
.IR enslave (1)
script.
.PP
With the \fB\-q\fP option (query), it tries to contact a server
already running on the specified host.  If it succeeds, it prints the
PID of that server.  
.PP
With the \fB\-k\fP option, mslavedc tries to kill any \fImslaved\fP 
process already running on the local host.
.PP
If neither \fB\-k\fP nor \fB\-q\fP is given, \fImslavedc\fP 
expects the pathname of 
.IR mslaved (8)
as an argument.  A datagram socket is created and 
\fImslaved\fP is \fIexec\fP'ed with the socket as standard input. The
\fB\-p\fP option may be used to specify a port number other than the
default of 9359.  The \fB\-n\fP option and its argument, if present,
are passed on to \fImslaved\fP to set its nice value.
The \fB\-t\fP (timeout) option is also passed to
\fImslaved\fP; if not present, \fB\-t900\fP is used giving a timeout of
15 minutes.
.PP
.SH "SEE ALSO"
xms(1), bms(1), enslave(1), mslavedc(8)
.PP
.SH COPYRIGHT
.if n Copyright (C) 1990 Andreas Gustafsson (gson@niksula.hut.fi)
.if t Copyright \(co 1990 Andreas Gustafsson (gson@niksula.hut.fi)
