.TH MSLAVED 8 "20 Jul 1991" "MandelSpawn 0.06"
.SH NAME 
mslaved \- MandelSpawn computation server
.SH SYNOPSIS  
.B mslaved 
[
.B \-t
timeout ] [
.B \-n
niceval ]
.SH DESCRIPTION  
.I mslaved
is the computation server daemon for MandelSpawn (see 
.I xms (1)
and
.IR bms (1)).
It accepts requests for calculating rectangles of pixels on its 
standard input, which should be a datagram socket.  
Normally \fImslaved\fP is started on demand
by 
.IR inetd (8C);
it may also be started manually using 
.IR mslavedc (8),
as in
.PP
	mslavedc ./mslaved
.PP
To spawn 
.I mslaved
processes on multiple machines, use
.IR enslave (1).
.PP
Note that
.I mslaved 
can \fInot\fP be started directly from the shell without using
.I mslavedc
or
.IR enslave .
.PP
The \fB\-n\fP option specifies a nice value; if no \fB\-n\fP option
is present, nice 10 will be used.  Use \fB\-n0\fP for no nice.
The \fB\-t\fP option specifies a timeout: \fImslaved\fP will exit
if no calculation requests are
received within the given number of seconds.  The default
timeout is 60 seconds, \fB\-t0\fP means never time out.
.SH "SEE ALSO"
xms(1), bms(1), enslave(1), mslavedc(8)
.PP
.SH COPYRIGHT
.if n Copyright (C) 1990, 1991 Andreas Gustafsson (gson@niksula.hut.fi)
.if t Copyright \(co 1990, 1991 Andreas Gustafsson (gson@niksula.hut.fi)
