.TH SCAT 1 "" 10 Dec 1990
.SH NAME
scat \(em speech cat
.SH SYNOPSIS
scat [-v vol] [-d directory]
.sp
.SH DESCRIPTION
Scat catenates english text from standard input to the audio device
on a sparcstation.
.SH OPTIONS
.TP 8
.B \-v vol
Specify the output volume from 0.0 to 1.0.
.TP 8
.B \-d directory
Specify a directory of prerecorded phonemes to be used to construct the
speech.  Each phoneme should be in a separate Sun audio file.
Each file should be named for its phoneme.
.SH SEE ALSO
speak(3), audio(4), audio_intro(3), audio_filehdr(3)
