#                        Copyright (c) 1987 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: mgrplot.1g,v 4.1 88/06/21 14:03:10 bianchi Exp $
#	$Source: /tmp/mgrsrc/demo/plot/RCS/mgrplot.1g,v $

.TH MGRPLOT 1G "August 21, 1987"
.AT 3
.SH NAME
mgrplot \- \fBplot\fP graphics filter for an 
.I MGR
terminal.
.SH SYNOPSIS
.B mgrplot < 
.I plot_file
.SH DESCRIPTION
This command reads plotting instructions (see
.IR  plot (5))
from the standard input and
produces plotting instructions suitable for an 
.I MGR
window
on its standard output.
Several options may be passed to 
.B mgrplot
through the environment variables:
.TP
MAX_X"
The maximum 
.I X
value will not exeed
.I MAX_X,
which defaults to 999.
.TP
MAX_Y"
The maximum 
.I Y
value will not exeed
.I MAX_Y,
which defaults to 999.
.TP
WINDOW_ID"
Switch to alternate window
.I
window_id
before starting plot, then switch back to the primary window upon
completion.
.TP
PAUSE"
Wait for the user to key
.I RETURN
after each plot.
.TP
DEBUG"
Print debugging information on
.I stderr.
.SH "SEE ALSO"
plot(3X), plot(3F), plot(5), mgr(1L)
