gcc -c alglobal.s
gcc -c ari68000.s
gcc -c array.s
gcc -c charstrg.s
gcc -c control.s
gcc -c debug.s
gcc -c eval.s
gcc -c hashtabl.s
gcc -c io.s
gcc -c lisparit.s
gcc -c list.s
gcc -c misc.s
gcc -c package.s
gcc -c pathname.s
gcc -c predtype.s
gcc -c record.s
gcc -c sequence.s
gcc -c spvw.s
gcc -c spvwtabf.s
gcc -c spvwtabo.s
gcc -c spvwtabs.s
gcc -c stream.s
gcc -c symbol.s
