# %W% %G% %U%
#
#   (c) Copyright 1991 by David M. Siegel.
#       All rights reserved.

include ../$(VPATH)/include/conf.mk

HDRS =       conf.h
OTHER_SRCS = conf.mk

include dummy.mk
include sccs.mk
