.TH color 1L "November 15, 1987"
.SH NAME
Color \- set the forground and background color for text in an
.B Mgr 
window.
.B MGR .
.SH SYNOPSIS
color [dark|light] \fIcolor\fP on [dark|light] \fIcolor\fP
.SH DESCRIPTION
.B color
sets the current foreground and background text color for an 
.B Mgr
window.
.I Color
is one of
black, white, red, green, blue, yellow, cyan or magenta.
Alternately,
.I color
may be specified as an index in the color lookup table.
.B Color
calls
.I set_colormap(1L)
to initialize the color map.
.SH SEE ALSO
mgr(1L)
set_colormap(1L)
.SH BUGS
.B Color
only works with
.I "color Mgr" .
.SH AUTHOR
S. A. Uhler
