.\"{{{  title
.TH cursor 1
.\"}}}  
.\"{{{  name
.SH NAME
cursor \(em change appearance of cursor
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B cursor
.BR n | b | u | l | r | i
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Cursor
changes the appearance of the cursor.
.\"}}}  
.\"{{{  options
.SH OPTIONS
.IP \fBn\fP
normal
.IP \fBb\fP
box
.IP \fBu\fP
underline
.IP \fBl\fP
left 
.IP \fBr\fP
right
.IP \fBi\fP
invisible
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
