.\"                        Copyright (c) 1988 Bellcore
.\"                            All Rights Reserved
.\"       Permission is granted to copy or use this program, EXCEPT that it
.\"       may not be sold for profit, the copyright notice must be reproduced
.\"       on copies, and credit should be given to Bellcore where it is due.
.\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
.\"
.TH font 1 "April 30, 1985"
.SH NAME
font \- change to a new font in a
.I mgr
window.
.SH SYNOPSIS
.B font
[ \fB<font number>\fP ]
.SH DESCRIPTION
.B font
Changes the current font to the number indicated,
or to the default font if
.I font number
is omitted.
.SH SEE ALSO
mgr(1L)
.SH AUTHOR
S. A. Uhler
