.\"{{{  title
.TH loadfont 1
.\"}}}  
.\"{{{  name
.SH NAME
loadfont \(em load font to server
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B loadfont 
.RB [ \-c ] 
.I font-name 
.I font-number
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
Load the given font-name into the given font number.
.\"}}}  
.\"{{{  options
.SH OPTIONS
.IP \fB\-c\fP
Make the given font the current font.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
