.\"{{{}}}
.\"{{{  title
.TH MENU 1 "October 11, 1992"
.\"}}}
.\"{{{  name
.SH NAME
menu \- create or select an mgr pop-up menu
.\"}}}
.\"{{{  synopsis
.SH SYNOPSIS
.B menu
.RB [ \-s\fP\fIn ]
.RB [ \-l\fP\fIn ]
.RB [ \-n\fP\fIname ]
.RB [ \-f\fP\fIn ]
.RB [ \-d\fP\fIname ]
.RI [ menufile ]
\&...
.\"}}}
.\"{{{  description
.SH DESCRIPTION
.I Menu
downloads or selects a pop-up menu for the MGR window manager.
.sp
The named input files (or standard input by default) should contain one
item-action pair per line, delimited by by one or more delimiter
characters (TABs by default).  Items and actions are arbitrary character
strings not containing the delimiter character.  The items are displayed
in the pop-up menu, and the user is allowed to select an item using the
mouse and middle button.  The corresponding action string is then
written to the standard input of the process running in the window.  If
an action ends with \\c, the newline character following the action is
suppressed.
.sp
Optionally, the menu file may begin with a \fBdelim=\fP\fIchar\fP line
to specify an alternate delimiter, followed by any number of
name=anything lines to specify one or more lines of menu name, and a
font=n line to select a font.
.\"}}}
.\"{{{  options
.SH OPTIONS
.\"{{{  -sn
.IP \fB\-s\fP\fIn\fP
selects the menu previously loaded into position n; that is, it binds
the menu in position n to the middle mouse button.  No downloading takes
place.
.sp
\fB\-s\fP by itself allows downloading of a new menu, without it being selected.
.\"}}}
.\"{{{  -ln
.IP \fB\-l\fP\fIn\fP
causes loading of a new menu into position \fIn\fP.  By default, \fIn\fP
is 1.  The loaded menu is also selected (unless \fB-s\fP was specified).
.\"}}}
.\"{{{  -nname
.IP \fB\-n\fP\fIname\fP
specifies a name for the menu.  Alternatively, a name may be specified
by one or more lines of the form \fBname=\fP\fIanything\fP in the menu file.  By
default, the name of the menu is taken to be the name of the input file
converted to upper-case.  The menu's name is displayed at the top of the
menu.
.sp
\fB\-n\fP by itself suppresses the name altogether.
.\"}}}
.\"{{{  -fn
.IP \fB\-f\fP\fIn\fP
specifies that the font loaded into font postion \fBn\fP will used for the
menu.  Default is 6.
.\"}}}
.\"{{{  -dchar
.IP \fB\-d\fP\fIchar\fP
indicates that \fIchar\fP will be used instead of the default, TAB, to
delimit items from actions in the menu file.
.\"}}}
.\"}}}
.\"{{{  bugs
.BUGS
The total number of characters in all actions and items may not exceed
approximately 1000.
.\"}}}
.\"{{{  examples
.ne 15
.SH EXAMPLES
.nf
menu <<!
delim=:
name=    FRUITS
name=--------------
apples:echo apples
oranges:echo oranges
pears:echo pears
passion fruit:echo passion fruit
three cherries:echo Jackpot!
!
.\"}}}
.\"{{{  author
.SH AUTHOR
Paul A. Tukey
.\"}}}
