'\"                        Copyright (c) 1988 Bellcore
'\"                            All Rights Reserved
'\"       Permission is granted to copy or use this program, EXCEPT that it
'\"       may not be sold for profit, the copyright notice must be reproduced
'\"       on copies, and credit should be given to Bellcore where it is due.
'\"       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.
'\"
'\"	$Header: shape.1,v 4.1 88/06/21 13:52:05 bianchi Exp $
'\"	$Source: /tmp/mgrsrc/doc/RCS/shape.1,v $
.TH shape 1L "April 30, 1985"
.SH NAME
shape \- Reshape
.I mgr
window.
.SH SYNOPSIS
.B shape
[ \fB<columns>\fP ]
[ \fB<rows>\fP ]
.SH DESCRIPTION
.B Shape
Reshapes the window to the specified number of 
.I columns
and
.I rows.
With no arguments
.I shape
makes an 
.I 80 column
by
.I 24 row
window.
With one argument,
.I shape
changes the number of lines to the number given,
leaving the number of columns unchanged.
.SH BUGS
Given unreasonable arguments,
.I shape
doesn't guarantee reasonable results
.SH SEE ALSO
mgr(1L)
.SH AUTHOR
S. A. Uhler
