.\"{{{  title
.TH SQUARE 1
.\"}}}  
.\"{{{  name
.SH NAME
square \(em square a window
.\"}}}  
.\"{{{  synopsis
.SH SYNOPSIS
.B square
.\"}}}  
.\"{{{  description
.SH DESCRIPTION
.B Square
squares a window.
.\"}}}  
.\"{{{  see also
.SH "SEE ALSO"
mgr(1)
.\"}}}  
.\"{{{  author
.SH AUTHOR
S. A. Uhler
.\"}}}  
