.\" $Id: tkdrop.man,v 2.0 1993/01/14 23:27:41 schwartz Exp $
.TH TKDROP 1 "13 December 1992"
.SH NAME
tkdrop \- a generic drag and drop representation of a filesystem object
.SH SYNOPSIS
.B tkdrop
.I command
.I id
.I icon
.I label
.I data
[
.I data ...
]
.SH REQUIREMENTS
This program is known to work with tk2.3 plus Michael J. McLennan's
drag&drop patches.
.SH DESCRIPTION
.LP
.B tkdrop
is a simple direct manipulation interface to a filesystem object.
It deals sensibly with files, executable or not, and directories.
.LP
The program presents an icon and a label in a small window.  
Double clicking the icon invokes user specified action.
Double clicking the label presents a handful of entry widgets
with which to customize the actions of the program.
.LP
The arguments and entry widgtes consist of the following.
.I command --
A shell command which will be executed upon user invokation.
The command is executed via /bin/sh -c "...".
.I id --
The name of the object being represented by the program.  
An environment variable named "id" will be set to the same value.
.I icon --
The icon displayed for the user.
.I label --
The label displayed for the user.
.I data --
Parameters passed to command as argv.

.SH AUTHOR
Scott Schwartz <schwartz@cs.psu.edu>

Thanks to Felix Lee <flee@cs.psu.edu> for lots of feedback.

.BUGS
Felix says it is klunky.

Sometimes focus gets lost.  The only way to get it back is to
unmap and remap the entry widgets.  Don't know why.
