 2199  1JZ
 2214 15MWRFQHRTSHRF RRHRN RRYQZR[SZRY
 2728 22I[NFMGMM RNGMM RNFOGMM RWFVGVM RWGVM RWFXGVM
 2275 12H]SFLb RYFRb RLQZQ RKWYW
 2274 42H\PBP_ RTBT_ RXIWJXKYJYIWGTFPFMGKIKKLMMNOOUQWRYT RKKMMONUPWQXRYTYXWZT[P[MZKXKWLVMWLX
 2271 32F^[FI[ RNFPHPJOLMMKMIKIIJGLFNFPGSHVHYG[F RWTUUTWTYV[X[ZZ[X[VYTWT
 2272 49F_[NZO[P\O\N[MZMYNXPVUTXRZP[M[JZIXIUJSPORMSKSIRGPFNGMIMKNNPQUXWZZ[[[\Z\Y RM[KZJXJUKSMQ RMKNMVXXZZ[
 2251  8MWRHQGRFSGSIRKQL
 2221 20KYVBTDRGPKOPOTPYR]T`Vb RTDRHQKPPPTQYR\T`
 2222 20KYNBPDRGTKUPUTTYR]P`Nb RPDRHSKTPTTSYR\P`
 2219  9JZRFRR RMIWO RWIMO
 2232  6E_RIR[ RIR[R
 2211  8MWR[QZRYSZS\R^Q_
  000  3KYNRVR
 2210  6MWRYQZR[SZRY
 2220  3G][BIb
 2200 40H\QFNGLJKOKRLWNZQ[S[VZXWYRYOXJVGSFQF RQFOGNHMJLOLRMWNYOZQ[ RS[UZVYWWXRXOWJVHUGSF
 2201 11H\NJPISFS[ RRGR[ RN[W[
 2202 45H\LJMKLLKKKJLHMGPFTFWGXHYJYLXNUPPRNSLUKXK[ RTFVGWHXJXLWNTPPR RKYLXNXSZVZXYYX RNXS[W[XZYXYV
 2203 47H\LJMKLLKKKJLHMGPFTFWGXIXLWNTOQO RTFVGWIWLVNTO RTOVPXRYTYWXYWZT[P[MZLYKWKVLUMVLW RWQXTXWWYVZT[
 2204 13H\THT[ RUFU[ RUFJUZU RQ[X[
 2205 39H]MFKP RKPMNPMSMVNXPYSYUXXVZS[P[MZLYKWKVLUMVLW RSMUNWPXSXUWXUZS[ RMFWF RMGRGWF
 2206 48H\WIVJWKXJXIWGUFRFOGMILKKOKULXNZQ[S[VZXXYUYTXQVOSNRNOOMQLT RRFPGNIMKLOLUMXOZQ[ RS[UZWXXUXTWQUOSN
 2207 31H\KFKL RKJLHNFPFUIWIXHYF RLHNGPGUI RYFYIXLTQSSRVR[ RXLSQRSQVQ[
 2208 63H\PFMGLILLMNPOTOWNXLXIWGTFPF RPFNGMIMLNNPO RTOVNWLWIVGTF RPOMPLQKSKWLYMZP[T[WZXYYWYSXQWPTO RPONPMQLSLWMYNZP[ RT[VZWYXWXSWQVPTO
 2209 48H\XMWPURRSQSNRLPKMKLLINGQFSFVGXIYLYRXVWXUZR[O[MZLXLWMVNWMX RQSORMPLMLLMIOGQF RSFUGWIXLXRWVVXTZR[
 2212 12MWRMQNROSNRM RRYQZR[SZRY
 2213 14MWRMQNROSNRM RR[QZRYSZS\R^Q_
 2241  4F^ZIJRZ[
 2238  6E_IO[O RIU[U
 2242  4F^JIZRJ[
 2215 32I[MJNKMLLKLJMHNGPFSFVGWHXJXLWNVORQRT RSFUGVHWJWLVNTP RRYQZR[SZRY
 2273 56E`WNVLTKQKOLNMMPMSNUPVSVUUVS RQKOMNPNSOUPV RWKVSVUXVZV\T]Q]O\L[JYHWGTFQFNGLHJJILHOHRIUJWLYNZQ[T[WZYYZX RXKWSWUXV
 2001 18H\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[
 2002 45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUP RUFWGXHYJYLXNWOUP RMPUPXQYRZTZWYYXZU[I[ RUPWQXRYTYWXYWZU[
 2003 32G\XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXXYV RQFOGMILKKNKSLVMXOZQ[
 2004 30G]LFL[ RMFM[ RIFSFVGXIYKZNZSYVXXVZS[I[ RSFUGWIXKYNYSXVWXUZS[
 2005 22G\LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[Y[YUX[
 2006 20G[LFL[ RMFM[ RSLST RIFYFYLXF RMPSP RI[P[
 2007 40G^XIYLYFXIVGSFQFNGLIKKJNJSKVLXNZQ[S[VZXX RQFOGMILKKNKSLVMXOZQ[ RXSX[ RYSY[ RUS\S
 2008 27F^KFK[ RLFL[ RXFX[ RYFY[ RHFOF RUF\F RLPXP RH[O[ RU[\[
 2009 12MXRFR[ RSFS[ ROFVF RO[V[
 2010 20KZUFUWTZR[P[NZMXMVNUOVNW RTFTWSZR[ RQFXF
 2011 27F\KFK[ RLFL[ RYFLS RQOY[ RPOX[ RHFOF RUF[F RH[O[ RU[[[
 2012 14I[NFN[ ROFO[ RKFRF RK[Z[ZUY[
 2013 30F_KFK[ RLFRX RKFR[ RYFR[ RYFY[ RZFZ[ RHFLF RYF]F RH[N[ RV[][
 2014 21G^LFL[ RMFYY RMHY[ RYFY[ RIFMF RVF\F RI[O[
 2015 44G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF
 2016 29G]LFL[ RMFM[ RIFUFXGYHZJZMYOXPUQMQ RUFWGXHYJYMXOWPUQ RI[P[
 2017 64G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF RNYNXOVQURUTVUXV_W`Y`Z^Z] RUXV\W^X_Y_Z^
 2018 45G]LFL[ RMFM[ RIFUFXGYHZJZLYNXOUPMP RUFWGXHYJYLXNWOUP RI[P[ RRPTQURXYYZZZ[Y RTQUSWZX[Z[[Y[X
 2019 34H\XIYFYLXIVGSFPFMGKIKKLMMNOOUQWRYT RKKMMONUPWQXRYTYXWZT[Q[NZLXKUK[LX
 2020 16I\RFR[ RSFS[ RLFKLKFZFZLYF RO[V[
 2021 23F^KFKULXNZQ[S[VZXXYUYF RLFLUMXOZQ[ RHFOF RVF\F
 2022 15H\KFR[ RLFRX RYFR[ RIFOF RUF[F
 2023 24F^JFN[ RKFNV RRFN[ RRFV[ RSFVV RZFV[ RGFNF RWF]F
 2024 21H\KFX[ RLFY[ RYFK[ RIFOF RUF[F RI[O[ RU[[[
 2025 20H]KFRQR[ RLFSQS[ RZFSQ RIFOF RVF\F RO[V[
 2026 16H\XFK[ RYFL[ RLFKLKFYF RK[Y[YUX[
 2223 12KYOBOb RPBPb ROBVB RObVb
  804  3KYKFY^
 2224 12KYTBTb RUBUb RNBUB RNbUb
 2262 11JZPLRITL RMORJWO RRJR[
  999  3JZJ]Z]
 2252  8MWSFRGQIQKRLSKRJ
 2101 39I]NONPMPMONNPMTMVNWOXQXXYZZ[ RWOWXXZZ[[[ RWQVRPSMTLVLXMZP[S[UZWX RPSNTMVMXNZP[
 2102 33G\LFL[ RMFM[ RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIFMF
 2103 28H[WPVQWRXQXPVNTMQMNNLPKSKULXNZQ[S[VZXX RQMONMPLSLUMXOZQ[
 2104 36H]WFW[ RXFX[ RWPUNSMQMNNLPKSKULXNZQ[S[UZWX RQMONMPLSLUMXOZQ[ RTFXF RW[[[
 2105 31H\LSXSXQWOVNTMQMNNLPKSKULXNZQ[S[VZXX RWSWPVN RQMONMPLSLUMXOZQ[
 2106 22KXUGTHUIVHVGUFSFQGPIP[ RSFRGQIQ[ RMMUM RM[T[
 2107 60I\QMONNOMQMSNUOVQWSWUVVUWSWQVOUNSMQM RONNPNTOV RUVVTVPUN RVOWNYMYNWN RNUMVLXLYM[P\U\X]Y^ RLYMZP[U[X\Y^Y_XaUbObLaK_K^L\O[
 2108 28G]LFL[ RMFM[ RMPONRMTMWNXPX[ RTMVNWPW[ RIFMF RI[P[ RT[[[
 2109 18MXRFQGRHSGRF RRMR[ RSMS[ ROMSM RO[V[
 2110 25MXSFRGSHTGSF RTMT_SaQbObNaN`O_P`Oa RSMS_RaQb RPMTM
 2111 27G\LFL[ RMFM[ RWMMW RRSX[ RQSW[ RIFMF RTMZM RI[P[ RT[Z[
 2112 12MXRFR[ RSFS[ ROFSF RO[V[
 2113 44BcGMG[ RHMH[ RHPJNMMOMRNSPS[ ROMQNRPR[ RSPUNXMZM]N^P^[ RZM\N]P][ RDMHM RD[K[ RO[V[ RZ[a[
 2114 28G]LML[ RMMM[ RMPONRMTMWNXPX[ RTMVNWPW[ RIMMM RI[P[ RT[[[
 2115 36H\QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM
 2116 36G\LMLb RMMMb RMPONQMSMVNXPYSYUXXVZS[Q[OZMX RSMUNWPXSXUWXUZS[ RIMMM RIbPb
 2117 33H]WMWb RXMXb RWPUNSMQMNNLPKSKULXNZQ[S[UZWX RQMONMPLSLUMXOZQ[ RTb[b
 2118 23IZNMN[ ROMO[ ROSPPRNTMWMXNXOWPVOWN RKMOM RK[R[
 2119 32J[WOXMXQWOVNTMPMNNMOMQNRPSUUWVXW RMPNQPRUTWUXVXYWZU[Q[OZNYMWM[NY
 2120 16KZPFPWQZS[U[WZXX RQFQWRZS[ RMMUM
 2121 28G]LMLXMZP[R[UZWX RMMMXNZP[ RWMW[ RXMX[ RIMMM RTMXM RW[[[
 2122 15I[LMR[ RMMRY RXMR[ RJMPM RTMZM
 2123 24F^JMN[ RKMNX RRMN[ RRMV[ RSMVX RZMV[ RGMNM RWM]M
 2124 21H]LMW[ RMMX[ RXML[ RJMPM RTMZM RJ[P[ RT[Z[
 2125 22H[LMR[ RMMRY RXMR[P_NaLbKbJaK`La RJMPM RTMZM
 2126 16I[WML[ RXMM[ RMMLQLMXM RL[X[XWW[
 2225 40KYTBRCQDPFPHQJRKSMSOQQ RRCQEQGRISJTLTNSPORSTTVTXSZR[Q]Q_Ra RQSSUSWRYQZP\P^Q`RaTb
 2229  3NVRBRb
 2226 40KYPBRCSDTFTHSJRKQMQOSQ RRCSESGRIQJPLPNQPURQTPVPXQZR[S]S_Ra RSSQUQWRYSZT\T^S`RaPb
 2246 24F^IUISJPLONOPPTSVTXTZS[Q RISJQLPNPPQTTVUXUZT[Q[O
\-     3E_IR[R
:A    30H\RFK[ RRFY[ RRIX[ RMUVU RI[O[ RU[[[ RLDKELFMELD RXDWEXFYEXD
:a    51I]NONPMPMONNPMTMVNWOXQXXYZZ[ RWOWXXZZ[[[ RWQVRPSMTLVLXMZP[S[UZWX RPSNTMVMXNZP[ RNFMGNHOGNF RWFVGWHXGWF
:O    56G]QFNGLIKKJOJRKVLXNZQ[S[VZXXYVZRZOYKXIVGSFQF RQFOGMILKKOKRLVMXOZQ[ RS[UZWXXVYRYOXKWIUGSF RLBKCLDMCLB RXBWCXDYCXB
:o    48H]QMNNLPKSKULXNZQ[S[VZXXYUYSXPVNSMQM RQMONMPLSLUMXOZQ[ RS[UZWXXUXSWPUNSM RMFLGMHNGMF RVFUGVHWGVF
:U    35F^KFKULXNZQ[S[VZXXYUYF RLFLUMXOZQ[ RHFOF RVF\F RLAKBLCMBLA RXAWBXCYBXA
:u    40G]LMLXMZP[R[UZWX RMMMXNZP[ RWMW[ RXMX[ RIMMM RTMXM RW[[[ RMFLGMHNGMF RVFUGVHWGVF
ss    46G\J[O[ RL[LIMGPFRFUGVIVLUNTORPPP RRFTGUIULTNRPTPWQXRYTYVXXVZS[Q[ RTPVQWRXTXVWXUZS[ RM[MINGPF
