.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH ED 1 "25 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
ed \- text editor
.SH SYNOPSIS
.BR "ed [ \- ] [ " name " ]"
.SH DESCRIPTION
.B ed
is a text editor.  This version is copyrighted, but freely available.  The
assumption is that the only use for
.B ed
will be to support scripts which use it.  Therefore, this documentation is
intentionally brief.  One hopes that this version of
.B ed
is fully compatible with the "standard" version.
.SH OPTIONS
.TP
.B \-
Suppress explanatory output.  This option should be used when the standard
input is an editor script.
.SH "SEE ALSO"
.nf
B. W. Kernighan,
.I A Tutorial Introduction to the ED Text Editor
.sp
B. W. Kernighan,
.I Advanced editing on UNIX
.fi
.sp
.BR sed (1),
.BR vi (1),
.BR ex (1),
.BR emacs (1)
.SH BUGS
This version does not support the
.B \-x
option for file encryption, the
.B x
command (traditionally for file encryption) does something else, and the
.B u
command (undo) is not supported.
.SH AUTHORS
Brian Beattie, Kees Bot, and others
.sp
25Aug92: (W.Metzenthen) Changed malloc() call to calloc() in makebitmap()
to remove bugs under Linux. Changed a few '^' to the correct '~'.  General
tidying. Recognize Linux via the __linux__ symbol.  Main change based upon
suggestion by Wolfgang Thiel.

