.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH HOSTNAME 1 "26 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
hostname \- set or print name of current host
.SH SYNOPSIS
.BR "hostname [ " host " ]"
.SH DESCRIPTION
.B hostname
prints the name of the current host, from the
.BR gethostname (2)
system call.  If an argument is present and the real or effective UID is 0,
.B hostname
changes the name of the host, with the
.BR sethostname (2)
system call.  This is usually done at boot time in the
.I /etc/rc.local
script.
.SH FILES
.I /etc/rc.local
.SH "SEE ALSO"
.BR gethostname (2),
.BR sethostname (1)
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
