.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH KILL 1 "24 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
kill \- terminate a process with extreme prejudice
.SH SYNOPSIS
.BR "kill [ \-" signal " ] " "pid ..."
.br
.B "kill -l"
.SH DESCRIPTION
.B kill
sends the specified signal to the specified process.  If no signal is
specified, the TERM signal is sent.  The TERM signal will kill processes
which do not catch this signal.  For other processes, if may be necessary
to use the KILL (9) signal, since this signal cannot be caught.

Most modern shells have a builtin kill function.
.SH OPTIONS
.TP
.BR \-l " and " \-?
Print a list of signal names.  These are found in
.I /usr/include/linux/signal.h
.SH "SEE ALSO"
.BR bash (1),
.BR tcsh (1),
.BR kill (2),
.BR sigvec (2)
.SH AUTHOR
Peter MacDonald
