.\" Copyright 1992 David Engel (david@ods.com)
.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" Most of this was copied from the README file.  Do not restrict distribution.
.\" May be distributed under the GNU General Public License
.TH LDD 1 "25 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
ldd \- print the shared libraries required to specified programs
.SH SYNOPSIS
.BR "ldd [ \-v ]"
prog ...
.SH DESCRIPTION
.B ldd
forks and execs each program with argc equal to zero.  The code which
normally loads the shared libraries, notices this special case and simply
prints the required libraries and exits.
.SH OPTIONS
.TP
.B \-v
Print the version number of the
.B ldd
binary.
.SH BUGS
.B ldd
will
.I not
work with some very old programs which were linked before
.B ldd
support was added to the compiler releases.  If you use
.B ldd
on one of these programs, the program will attempt to run with argc = 0 and
the results will be unpredictable.
.SH AUTHOR
V1.0 and V1.1: David Engel (david@ods.com)

