.TH WALL 1
.SH NAME
wall \(em send a message to everybody's terminal.
.SH SYNOPSIS
.B wall
.RB [message]
.SH DESCRIPTION
.B Wall
sends a message to everybody logged in with their \fImesg\fP(1) permission
set to \fByes\fP. The message can be given as an argument to \fIwall\fP, or
it can be sent to \fIwall\fP's standard input. When using the standard input
from a terminal, the message should be terminated with the \fBEOF\fP key
(usually Control-D).
.SH SEE ALSO
mesg(1).
.SH AUTHOR
Miquel van Smoorenburg, miquels@drinkel.nl.mugnet.org
