.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH WRITE 1 "26 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
write \- write to another user
.SH SYNOPSIS
.B write
user ...
.SH DESCRIPTION
This
.B write
is a stripped-down version of a regular
.B write
command.  This command allows a single message to be sent to the users
listed on the command line.  The message will be sent to all of the users
listed, on each tty onto which they are logged in.  The message is
terminated with the end-of-line character (usually a control-D).

Permission to write to a specific user's tty is granted or removed with the
.B mesg (1)
command (or by changing the permissions on the tty so that other users
cannot write to it).
.SH FILES
.I /etc/utmp
.SH "SEE ALSO"
.BR mesg (1),
.BR who (1),
.BR mail (1),
.BR talk (1),
.BR wall (1)
.SH BUGS
No interactive features are supported.
.SH AUTHOR
Peter Orbaek (poe@daimi.aau.dk)
