.SH
Additional Features
.PP
Several options can be included in any of the individual instrument parts
within a section.  A sample statement follows the description of each option.
The keyword which follows the `!' in these statements may be abbreviated
to the first two characters.
.SH
Key Signatures
.PP
Any desired key signature is specified by listing the accidentals as they
occur in a key signature statement. Thereafter, all notes of that
instrument part are sharpened or flattened accordingly. For example, for the
key of D, type
.i
!key "#fc"
.e
.SH
Accidental Following
.PP
Accidental following may be turned on or off as needed.  When turned off,
accidentals no longer carry throughout the measure as in traditional
notation.  This convention is sometimes used in contemporary scores.
.sp 1
.i
!accidentals "off"
.e
.SH
Octave Following
.PP
Turning off octave following indicates that pitches stay in the same absolute
octave register until explicitly moved. An absolute octave starts at pitch
c and ends at the b above it.  The octave middle-c-to-b is
indicated with an equals sign (`=') and octave displacement is indicated with
the appropriate number of commas or apostrophes. These displacements are
cummulative.  For example,
.i
.ne 2
!octaves "off"
4='c g b 'c
.e
starts at the c above middle c and ends at two c's above middle c.
.SH
Vertical Following
.PP
Turning off vertical following means that durations, register, and
parameters only carry horizontally from note to note and not vertically
as described in the section on divisi.
.i
!vertical "off"
.e
.SH
Transposition
.PP
Any instrument part can be transposed to another key by indicating the
intervalic difference between the notated key and the desired key.
This difference is always taken with reference to middle c - to transpose
a whole step upward, for example, type
.i
!transpose "d"
.e
This indicates that the part is transposed by the interval difference between
middle c and d.
.SH
Next-value and Previous-value Parameteres
.PP
In order to play a note, it is sometimes necessary for an instrument to know
what value one or more parameters will have for the next note.	For instance,
an instrument might be designed which glisses during the last portion of
its performance (perhaps only when a slur is indicated) from its written
pitch to the pitch of the next note.  This can only be done, of course, if
the instrument can know what the pitch of the next note will be.
.pg
The necessary information can be provided using next-value parameters.
A next value parameter might be declared by
.i
!next p5 "p6"
.e
which is interpreted to mean that for the current instrument, p6 will
contain the next note's p5 value. This holds true globally for all occurences
of this instrument until further modifications.
If for any reason you wish to override
this value, p6 may be filled in explicitly.  This is sometimes useful for
the last note of a section, for which p6 will otherwise assume the p5
value for the current note.  The \fInext-value\fR feature is illustrated in
the Scot example II.
.PP
The necessary information may also be provided using
\fIstandard numeric score\fR next-value parameters.
A parameter argument containing the symbol npx (where x is an integer)
will substitute parameter number x of the following note for
that instrument.
Similarly, the value of a parameter occurring during the previous note may
be referenced with the symbol ppx (where x is an integer).  Details of the
next- and previous-value parameter feature may be found in the
.B
Numeric Scores
.R
section.
.SH "RAMPING"
.PP
Pfields containing the symbol < will be replaced by values derived from linear
interpolation of a time-based ramp.  Ramp endpoints are defined by the first
real number found in the same pfield of a preceding and following note played
by the same instrument.  Details of the ramping feature are likewise found
in the
.B
Numeric Scores
.R
section.
.SH
f0 Statements
.PP
In each score section, Scot automatically produces an f0 statement with a
p2 equal to the ending time of the last note or rest in the section.
Thus, `dead time' at the end of a section for reverberation decay or whatever
purpose may be specified musically by rests in one or more parts.
See the eighth rest at the end of Scot example II and its
output score shown below.
.bp
.SH
Output Scores
.PP
Output file
.I score
from Scot Example I.
.i
f1 0 512 10 1 .5 .25 .126
f2 0 256  7 1 120 1 8 0 128 1
i1.01 0 1 0 8.00
i1.01 1 0.5 0 8.02
i1.01 1.5 0.5 0 8.03
i1.01 2 0.5 0 8.05
i1.01 3 1 0 9.00
i1.01 4 0.75 0 8.10
i1.01 4.75 0.25 0 8.09
i1.01 5 0.25 0 8.08
i1.01 5.25 0.25 0 8.07
i1.01 5.5 0.25 0 8.06
i1.01 5.75 0.25 0 8.05
i1.01 6 1 0 8.03
i1.01 7 1 0 8.00
i2.01 0 2 0 6.00
i2.01 2 2 0 6.08
i2.01 4 2 0 6.07
i2.01 6 2 0 7.00
t0 60
f0 8
s
i1.01 0 0.6667 0 9.00
i1.01 1.3333 0.6667 0 9.00
i1.01 2 1.75 0 9.02
i1.01 3.75 0.25 0 9.03
i1.01 4 0.6667 0 9.05
i1.01 5.3333 0.6667 0 9.05
i1.01 6 1.75 0 9.07
i1.01 7.75 0.25 0 9.09
i2.01 0 1 0 6.00
i2.01 1 1 0 6.07
i2.01 2 1 0 6.00
i2.01 3 1 0 6.07
i2.01 4 2 0 7.08
i2.01 6 2 0 7.07
t0 60
f0 8
s
.e


	Output file
.I score
from Scot Example II.
.i
f1 0 256 10 1
c r1 n 7 5
c r1 n 8 6
i1.01 0.5000 0.5000 0 8.00 3 8.00 3
i1.02 0.5000 0.5000 0 8.04 3 8.05 3
i1.03 0.5000 0.5000 0 8.07 3 8.09 3
i1.01 1.5000 0.5000 0 8.00 3 8.01 3
i1.02 1.5000 0.5000 0 8.05 3 8.07 3
i1.03 1.5000 0.5000 0 8.09 3 8.10 3
i1.01 2.5000 0.5000 0 8.01 3 8.00 5
i1.02 2.5000 0.5000 0 8.07 3 8.05 5
i1.03 2.5000 0.5000 0 8.10 3 8.09 5
i1.01 3.5000 0.5000 0 8.00 5 8.02 5
i1.02 3.5000 0.5000 0 8.05 5 8.05 5
i1.01 4.0000 1.0000 1 8.02 5 8.00 5
i1.03 3.5000 1.0000 0 8.09 5 8.07 5
i1.01 5.0000 1.0000 2 8.00 5 8.00 5
i1.02 4.0000 1.5000 0 8.05 5 8.04 5
i1.02 5.5000 0.5000 0 8.04 5 8.05 5
i1.03 4.5000 1.5000 0 8.07 5 8.05 5
i1.01 6.0000 1.5000 0 8.00 5 8.00 5
i1.02 6.0000 1.5000 0 8.05 5 8.05 5
i1.03 6.0000 1.5000 0 8.05 5 8.05 5
c r2 n 7 5
c r2 n 8 6
i2.01 0.0000 0.5000 0 7.00 3 7.05 3
i2.01 1.0000 0.5000 0 7.05 3 7.04 3
i2.01 2.0000 0.5000 0 7.04 3 7.05 3
i2.01 3.0000 0.5000 0 7.05 3 7.10 5
i2.01 4.0000 2.0000 1 7.10 5 7.09 5
i2.02 4.0000 1.0000 1 6.10 5 7.00 5
i2.02 5.0000 1.0000 2 7.00 5 7.05 5
i2.01 6.0000 1.5000 2 7.09 5 7.09 5
i2.02 6.0000 1.5000 0 7.05 5 7.05 5
t0 60 0.0000 90.0000 2.0000 90.0000 4.0000 80.0000 4.0000 90.0000
f0 8.0000
s
e
.e

