#!/bin/sh
# 2 segments of 1000 pages each
# add 2 attaches to each
trap 'date >> swap.log' SIGINT
sync
date >> swap.log 
shmswap a 1000 1 2>> swap.log &
# shmswap b 1000 1 2>> swap.log &
sleep 2;
swapat a 5 2 2>> swap.log &
swapat b 5 2 2>> swap.log &
swapat a 5 2 2>> swap.log &
swapat b 5 2 2>> swap.log &
echo type ^C to kill subprocesses.
wait
exit 0
