#
# Makefile for DOS machines running Borland C++
#

# Check for autodependencies (.H files)

.autodepend

CFLAGS = -ml -v -N -I..

#
# -ml = Large model
# -v  = Debugging information on (you may want to remove this)
# -N  = Stack checking on (I would recommend this for the time being...)
#

.c.obj:
	bcc -c $(CFLAGS) $<

richtext: richtext.exe

richtext.exe: richtext.obj richlex.obj
        tlink c0l richtext richlex,richtext,,cl;
