.TH XPUZZLE 6 "February 1987"
.UC 4
.SH NAME
xpuzzle \- another X-window V11 puzzle game
.SH SYNOPSIS
.B xpuzzle
[
.B options
]
.SH DESCRIPTION
The goal of this game is to move down the largest piece to the bottom in 
minimal number of movements.  It is known that the puzzle can be solved in 
86 movements.  To move a piece, point it by the mouse and press a button,
hold the button until you move the mouse to an adjacent empty
square.  
.br
If you want to quit, press 'q' or 'Q' on the keyboard, while the cursor is
in the puzzle window.

The following options are valid:
.PP
.TP 8
.B -fg color
as usual - change foreground color
.TP 8
.B -bg color
as usual - change background color
.TP 8
.B -bd color
as usual - change border color
.TP 8
.B -bw number
as usual - change border width
.TP 8 
.B host:display
Name of the display you want the puzzle to run on.
.SH AUTHORS
.PP
Jiang-Hsing Chu (jchu@mimsy.umd.edu) original game for suntools
.PP
Claus Gittinger (..!decvax!unido!sinix!claus) X11 version
