.\"{{{}}}
.\"{{{  title
.TH GROPBM 1 "January 23, 1993"
.\"}}}
.\"{{{  name
.SH NAME
gropbm \- GNU roff driver for Hershey fonts
.\"}}}
.\"{{{  synopsis
.SH SYNOPSIS
.ad l
.B gropbm
.RB [ \-c
.IR cmd ]
.RB [ \-m ]
.RB [ \-x
.IR dpi-x ]
.RB [ \-y
.IR dpi-y ]
.RB [ \-w
.IR inch-wide ]
.RB [ \-l
.IR inch-long ]
.RB [ \-v ]
.ad b
.\"}}}
.\"{{{  description
.SH DESCRIPTION
\fBGropbm\fP is the GNU runoff driver to translate ditroff output using
Hershey fonts into either portable bitmaps (PBM) or Bellcore window
manager format (MGR).  MGR support is only available when specified at
compile time.
.\"}}}
.\"{{{  options
.SH OPTIONS
.\"{{{  -c cmd
.IP "\fB\-c\fP \fIcmd\fP"
Each page of output will be piped to \fIcmd\fP instead of written on
standard output.
.\"}}}
.\"{{{  -m
.IP \fB\-m\fP
Output will be in MGR format instead of PBM format.
.\"}}}
.\"{{{  -x dpi
.IP "\fB\-x\fP \fIdpi-x\fP"
Set x resolution in dots per inch, default is 72.
.\"}}}
.\"{{{  -y dpi
.IP "\fB\-y\fP \fIdpi-y\fP"
Set y resolution in dots per inch, default is 72.
.\"}}}
.\"{{{  -w inch-wide
.IP "\fB\-w\fP \fIinch-wide\fP"
Set bitmap width in inch, default is 8.
.\"}}}
.\"{{{  -l inch-long
.IP "\fB\-l\fP \fIinch-long\fP"
Set bitmap length in inch, default is 12.
.\"}}}
.\"{{{  -v
.IP "\fB\-v\fP"
Verbose, print page numbers on standard error.
.\"}}}
.\"}}}
.\"{{{  examples
.SH EXAMPLES
Previewing each page of output:
.sp
.in +.5i
.ad l
groff \-man \-Tpbm \-P\-m \-P\-v \-P\-c \-P'(cat > /tmp/gropbm$$; \e
.br
mgrview \-r /tmp/gropbm$$; rm /tmp/gropbm$$)' gropbm.1
.ad b
.in
.\"}}}
.\"{{{  see also
.SH "SEE ALSO"
groff(1), mgrview(1), pbm(5)
.\"}}}
.\"{{{  bugs
.SH BUGS
Drawing command other than line are not supported yet.
.\"}}}
.\"{{{  author
.SH AUTHOR
Michael Haardt
.\"}}}
.\"{{{  history
.SH HISTORY
This program is derived from my roff, which no longer exists.
.\"}}}
