.\" @(#)clock.1 1.23 90/02/26 SMI; 
.\" Updated 6/7/90
.TH CLOCK 1 "11 June 1990
.SH NAME
clock - display the time in an icon or window
.SH SYNOPSIS
.B clock
.SH AVAILABILITY
This command is available with the
OpenWindows environment.
For information about installing OpenWindows, refer to the
.I OpenWindows Installation and Start-Up Guide.
.SH DESCRIPTION
.LP
.B clock
is an OpenWindows XView utility that displays the current time in
a window or icon. When the window is open, 
.B clock 
can display
the time in  either analog or digital format. 
The clock window is scalable in either format.
.SH USAGE
When the
.B clock
window is open, it has a floating menu from which you can bring up a property
window.
From this property sheet, you can modify the display of the
tool by selecting either the 
.B Analog
or
.B Digital
choice box.
.RS
.B Seconds:
.RS
On the analog version, this selection starts a second hand on the
face of the clock. On the digital version, it adds two digits to
the digital readout.
.RE
.B Date:
.RS
Turns on a date display for both analog and digital versions of
.B clock.
.RE
.RE
.SH BUGS
If you reset the system time,
.B clock
will not reflect the new time until you change its window state from
open to icon, or vice versa.
To reset the system time, see
.B date
(1V).

The date display does not go well with the round clock face.

Occasionally, when 
.B clock
is uncovered, the face will be visually corrupted. Use the
.B Refresh
button from the frame menu to repair.
