#!/bin/sh

# $Header: /home/x_cvs/mit/server/ddx/x386/LinkKit/x386config.sh,v 1.4 1992/09/30 23:35:37 dawes Exp $
#
# Generate X386Conf.tmpl Imake template
#
# Link Kit version
#
# Usage: x386config.sh MODULETYPE1 module ... MODULETYPE2 module ...
#

Iconfig=X386Conf.tmpl

ModuleHeader=
ModuleList=
ExtraRenderers=NO

cat > $Iconfig <<EOF
XCOMM  --------------------------------------------------------------------
XCOMM  X386Conf.tmpl  -- configuration parameters for X386
XCOMM  This file is automatically generated -- DO NOT EDIT
XCOMM  --------------------------------------------------------------------

         X386SRC = drivers
    VGADRIVERSRC = \$(X386SRC)/vga256
   VGA2DRIVERSRC = \$(X386SRC)/vga2
     RENDERERSRC = renderers
#if X386MonoServer
     VGA2CONFOBJ = \$(X386SRC)/vga2/vga2Conf.o
  VGA2CONFSUBDIR = \$(X386SRC)/vga2
   X386MCONFOBJS = \$(VGA2CONFOBJ)
X386MCONFSUBDIRS = \$(VGA2CONFSUBDIR)
#endif
#if X386Server
      VGACONFOBJ = \$(X386SRC)/vga256/vga256Conf.o
   VGACONFSUBDIR = \$(X386SRC)/vga256
    X386CONFOBJS = \$(VGACONFOBJ)
 X386CONFSUBDIRS = \$(VGACONFSUBDIR)
#endif
 RENDERERCONFOBJ = \$(RENDERERSRC)/rendererConf.o
RENDERERCONFSUBDIR = \$(RENDERERSRC)
EOF

Done=NO
while [ $Done = NO ]; do
    Args="$*"
    case $1 in
        ''|VGADRIVER|VGA2DRIVER|RENDERER)
            if [ X"$ObjsHeader" != X ]; then
		if [ X"$ModuleObjs" = X ]; then
		    echo "$ObjsHeader" >> $Iconfig
		else
		    echo "$ObjsHeader \\" >> $Iconfig
		    set - $ModuleObjs
		    while [ $# -gt 1 ]; do
                        echo "                   $1 \\" >> $Iconfig
                        shift
                    done
                    echo "                   $1" >> $Iconfig
                    shift
		fi
	    fi
            if [ X"$SubdirsHeader" != X ]; then
		if [ X"$ModuleSubdirs" = X ]; then
		    echo "$SubdirsHeader" >> $Iconfig
		else
		    echo "$SubdirsHeader \\" >> $Iconfig
		    set - $ModuleSubdirs
		    while [ $# -gt 1 ]; do
                        echo "                   $1 \\" >> $Iconfig
                        shift
                    done
                    echo "                   $1" >> $Iconfig
                    shift
		fi
	    fi
            set - $Args
            ModuleType=$1
            ModuleObjs=
            ModuleSubdirs=
	    case $ModuleType in
                VGADRIVER)
                    ObjsHeader='         VGAOBJS ='
                    SubdirsHeader='      VGASUBDIRS ='
                    ;;
                VGA2DRIVER)
                    ObjsHeader='        VGA2OBJS ='
                    SubdirsHeader='     VGA2SUBDIRS ='
                    ;;
                RENDERER)
                    ObjsHeader='    RENDERERLIBS ='
                    SubdirsHeader=' RENDERERSUBDIRS ='
                    ;;
	    esac
	    ;;
        *)
            case $ModuleType in
                VGADRIVER)
                    ModuleObjs="$ModuleObjs "'$(VGADRIVERSRC)'/$1.o
                    ModuleSubdirs="$ModuleSubdirs $1"
                    ;;
                VGA2DRIVER)
                    ModuleObjs="$ModuleObjs "'$(VGA2DRIVERSRC)'/$1.o
                    ModuleSubdirs="$ModuleSubdirs $1"
                    ;;
                RENDERER)
                    ExtraRenderers=YES
                    ModuleObjs="$ModuleObjs "'$(RENDERERSRC)'/lib$1.a
                    ModuleSubdirs="$ModuleSubdirs "$1
                    ;;
            esac
            ;;
    esac
    if [ $# -eq 0 ]; then
        Done=YES
    else
        shift
    fi
done

echo "#define ExtraRenderers $ExtraRenderers" >> $Iconfig
