.\" -*- nroff -*-
.TH EFSCK 8 "Jan 1993" "Version alpha 12"
.SH NAME
efsck \- check a Linux extended file system
.SH SYNOPSIS
.B efsck
[
.B \-larvsdtS
]
[
.B \-b
.I filename
]
.I device
.SH DESCRIPTION
.B efsck
is used to check a Linux extended file system.
.br
.I device
is the special file corresponding to the device (e.g /dev/hdXX).
.SH OPTIONS
.TP
.I -l
List all the file names in the file system
.TP
.I -a
Automatically repair the file system without any questions (use
this option with caution).
.TP
.I -r
Interactively repair the file system (ask for confirmations).
.TP
.I -v
Verbose mode.
.TP
.I -s
List the super block before checking the file system.
.TP
.I -d
Print debugging output (useless unless you want to find a bug in
.B efsck
).
.TP
.I -t
Check the file system for bad blocks.
.TP
.I -S
Salvage (i.e. rebuild) the blocks and inodes free lists.
.TP
.I -b filename
Read the bad blocks list from
.I filename
.SH AUTHOR
.B efsck
is based on
.B fsck (8)
written by Linus Torvalds <torvalds@cs.helsinki.fi> for the
minix file system.
.br
Remy Card <card@masi.ibp.fr> has adapted it for the extended file
system and is maintaining it.
.br
Wayne Davison <davison@borland.com> has contributed lots of nice
features.
.SH BUGS
There is no support for a directory lost+found.
.br
When a mounted file system is checked, super block informations
are modified on the disk and not in the memory copy.
.br
Please report bugs to the author.
.SH AVAILABILITY
The most recent released version of efsck is always available for
anonymous ftp from ftp-masi.ibp.fr (132.227.64.26) in the directory
pub/linux/ALPHA/extfs.  A copy can also be found on tsx-11.mit.edu
in the directory pub/linux/ALPHA/extfs.
.SH SEE ALSO
.BR mkefs (8)
