.\" -*- nroff -*-
.TH MKEFS 8 "Jan 1993" "Version alpha 12"
.SH NAME
mkefs \- create a Linux extended file system
.SH SYNOPSIS
.B mkefs
[
.B \-c
| 
.B \-l
.I filename
]
[
.B \-i
.I bytes-per-inode
]
.I device
[
.I blocks-count
]
.SH DESCRIPTION
.B mkefs
is used to create a Linux extended file system on a device (usually
a disk partition).
.br
.I device
is the special file corresponding to the device (e.g /dev/hdXX).
.br
.I blocks-count
is the number of blocks on the device.  If omitted,
.B mkefs
automagically figures the file system size.
.SH OPTIONS
.TP
.I -c
Check the device for bad blocks before creating the file system
.TP
.I -l filename
Read the bad blocks list from
.I filename
.TP
.I -i bytes-per-inode
Specify the bytes/inode ratio. 
.B mkefs
creates an inode for every
.I bytes-per-inode
bytes of space on the disk.
.I bytes-per-inode
must be at least 1024.
.SH AUTHOR
.B mkefs
is based on
.B mkfs (8)
written by Linus Torvalds <torvalds@cs.helsinki.fi> for the
minix file system.
.br
Remy Card <card@masi.ibp.fr> has adapted it to the extended file
system and is maintaining it.
.br
Adam Richter <adam@soda.berkeley.edu> added the automatic file system
size detection.
.SH BUGS
There may be some.  Please, report them to the author.
.SH AVAILABILITY
The most recent released version of mkefs is always available for
anonymous ftp from ftp-masi.ibp.fr (132.227.64.26) in the directory
pub/linux/ALPHA/extfs.  A copy can also be found on tsx-11.mit.edu
in the directory pub/linux/ALPHA/extfs.
.SH SEE ALSO
.BR efsck (8)
