.Id $Id: at.1,v 1.6 1993/01/17 00:53:43 kernel Exp kernel $
.TH AT 1 "Jan 1993" local "Linux Programmer's Manual"
.SH NAME
at, batch \- queue jobs for later execution
.SH SYNOPSIS
.B at
.RB [ -q 
.IR queue ]
.B TIME
.RI [ " DATE " ]
.RI [ " < file " ]
.br
.B at -l
.br
.B at -d
.I job
.RI [ job... ]
.br
.B batch
.RI [ " < file " ]
.SH DESCRIPTION
.B at
and
.B batch
read commands from standard input which are to be executed at a later time.
.TP 8
.BR at
executes commands at a specified time, or lists or deletes jobs.
.TP 8
.BR batch
executes commands when system load levels permit; in other words, when the load average
as read from
.I /proc/loadavg
drops below a specified level.
.PP
.B At
without arguments expects a four \- digit \- time in the format
.B MMHH
to indicate 24\-hour time.
The optional date arguments is of the form
.B DDMMYY
or
.BR DDMMYYYY .
.PP
For both
.BR at " and " batch ,
chommands are read from standard input and executed.
The working directory at the time is maintained, as is the umask. The user
will be mailed standard error and standard output from his commands.
.SH OPTIONS
.TP 8
.B \-l
lists all jobs for the current user.
The columns are: Job\-Id, queue, execution time and execution date.
.TP 8
.BI \-q " queue"
put the job into a queue.
A queue designation consists of a single letter; valid queue designation range from
.B a
to 
.BR l .
The 
.B a
queue is the default,
.B b
the batch queue.
Queues with higher letters run with increased niceness.
.TP 8
.B \-d
treats all following arguments as jobnames and deletes them.
.SH FILES
.I /usr/spool/atjobs
.br
.I /proc/loadavg
.SH SEE ALSO
atrun(8), cron(1), nice(1)
.SH BUGS
Traditional access control to
.B at
and
.B batch
via the files
.I /usr/lib/at.allow
and
.I /usr/lib/at.deny
is not implemented.
.PP
The user will get mail after completion regardless of wether there was output or not.
.PP
The correct operation of
.B batch
depends on the presence of a
.IR proc -
type directory mounted on
.IR /proc .
