.Id $Id: atrun.8,v 1.3 1993/01/13 19:59:09 kernel Exp $
.TH ATRUN 8 "Jan 1993" local "Linux Programmer's Manual"
.SH NAME
atrun \- run jobs queued for later execution
.SH SYNOPSIS
.B atrun
.SH DESCRIPTION
.B atrun
runs jobs queued by
.BR at(1) .
Root's crontab file has to contain the line
.br
.B * * * * * /usr/lib/atrun
.br
so
.B /usr/lib/atrun
gets called once a minute.
.SH OPTIONS
None.
.SH WARNINGS
For
.B atrun
to work, you have to start up a
.B cron
daemon.
.SH FILES
.I /usr/spool/atjobs
.SH SEE ALSO
at(1), cron(1), crontab(1)
.SH BUGS
The functionality of 
.B atrun
should be merged into
.BR cron(1) .
