.TH UNTCX 1 "19 March 1993"
.UC Melb
.SH NAME
untcx \- Uncompress or execute tcx executables
.SH SYNOPSIS
untcx [-x | -u] filename [args]
.SH DESCRIPTION
\fBUntcx\fP performs three functions.  Firstly used as listed above, it
will uncompress an executable compressed with tcx(1), if such compression
is no longer desired.  If the \fB-x\fP option is specified, this will force
untcx to execute \fBfilename\fP, with \fBargs\fP as command line arguments.
.PP
If the \fB-u\fP option is given, this forces untcx into plain decompression
of \fBfilename\fP.  Note, that while this is the default mode of operation for
users other than root, it is required if the invoking user is root.  Under the
LINUX operating system, the -u option is ALWAYS required by any user if that
user wishes to explicitly uncompress an executable.
.PP
Secondly it is the tool which performs and transparant uncompression
and execution of executables compressed with tcx(1).  This mode of
operation is never directly seen by the user (otherwise it wouldn't
be transparent would it!).
.PP
Thirdly it invokes itself in a daemon mode which will keep track of
all executables operating withing the tcx system, to allow for
transparent recompression of executables that have been uncompressed
in the process of being invoked.  This mode of operation is also
transparent to the user.
.SH SEE ALSO
tcx(1)
.SH BUGS
Untcx is still in beta test stage, so there are bound to be some.
Please report any bugs or "patch"-style bug fixes (or new system ports)
or even just suggested improvements, via email to slf@cs.mu.OZ.AU
.SH AUTHOR
Stewart Forster, University Of Melbourne, 1993
