#!/bin/sh
# remove /etc/mtab* so mount creates the /etc/mtab file
/bin/rm -f /etc/mtab* /etc/nologin /etc/utmp
echo -n "" >> /etc/utmp

# You may wish to clip this one down as well
#/bin/mv -f /etc/wtmp /etc/wtmp.old
#touch /etc/wtmp
echo -n "" >> /etc/utmp

# should check fs before mounting
#e2fsck -av /dev/sda2

/bin/mount -av -t nonfs
/bin/swapon -a

/bin/rm -f /usr/spool/uucp/LCK*

/bin/sh /etc/rc.local
