.\" @(#)man/man8/pathmerge.an	1.3 8/2/92 03:32:46
.TH PATHMERGE X_MAN8_EXT_X "31 January 1988" "Local"
.SH NAME
pathmerge \- merge sorted paths files
.SH SYNOPSIS
.B X_UTIL_BIN_DIR_X/pathmerge
.I file ...
.SH DESCRIPTION
.I Pathmerge
takes a set of sorted path files, as produced by
.IR pathalias (8),
and generates on the standard output a merge of the path information,
with one path given for each hostname.  Precedence for paths goes to
the files given earlier in the argument list.  One of the filenames
given in the argument list can be
.B \-
to specify the standard input.
.PP
As an example of the use of pathmerge, let's say that we have two
files,
.I forces
and
.IR paths ,
whose contents are, respectively:
.ta \w'cbosgd'u+3n
.RS
.nf

ihnp4	cbosgd!ihnp4!%s
muts12	muts12!%s
sun	sun!%s

.fi
.RE
and
.RS
.nf

cbosgd	cbosgd!%s
ihnp4	ihnp4!%s
sun	ames!sun!%s
uunet	uunet!%s

.fi
.RE
The command
.I "``pathmerge forces paths''"
will produce on the standard output:
.RS
.nf

cbosgd	cbosgd!%s
ihnp4	cbosgd!ihnp4!%s
muts12	muts12!%s
sun	sun!%s
uunet	uunet!%s

.fi
.RE
.DT
For the purposes of pathmerge, a hostname is terminated by either a
space, a tab, a colon or a newline.
The number of
.I file
arguments is limited by the number of available file descriptors, as
all of the files are opened and read simultaneously.
.SH "SEE ALSO"
.IR mkline (X_MAN8_EXT_X),
.IR mksort (X_MAN8_EXT_X),
.IR mkdbm (X_MAN8_EXT_X),
.IR smail (X_MAN5_EXT_X),
.IR smail (X_MAN8_EXT_X),
.I mkpath (X_MAN8_EXT_X)
and
.IR pathalias (X_MAN8_EXT_X).
.SH COPYRIGHT
Copyright(C)1987, 1988 Ronald S. Karr and Landon Curt Noll
.br
Copyright(C)1992 Ronald S. Karr
.br
See a file COPYING,
distributed with the source code,
or type
.I "smail -bc"
for distribution rights and restrictions
associated with this software.
