.TH LIBEXPECT 3 "30 December 1992"
.SH NAME
libexptk \- programmed dialogue with interactive programs in a Tcl/Tk environment \- C functions
.SH SYNOPSIS
.nf
.B #include <exp_main.h>

.B cc files... \-lexptcl \-ltcl
.fi

.SH DESCRIPTION
This is a placeholder for a description of a library for programs that
want to use Expect with Tcl and Tk.  Until this entry is completed, use the
file exp_main_tk.c in the Expect distribution as a prototype main.
.SH AUTHOR
Don Libes, libes@cme.nist.gov, National Institute of Standards and Technology
.PP
Design and implementation of the
.B expect
library was paid for by the U.S. government and is therefore in the public
domain.
However the author and NIST would like credit
if this program and documentation or portions of them are used.
