	.file	"stdstrbufs.cc"
gcc2_compiled.:
.globl ___std_filebuf_0
.data
	.align 2
___std_filebuf_0:
	.long -72499064
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.word 0
	.space 2
	.long __vt$filebuf
	.word 0
	.space 10
	.space  0x100		# For future use
.globl ___std_filebuf_1
	.align 2
___std_filebuf_1:
	.long -72499068
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long ___std_filebuf_0
	.long 0
	.long 0
	.long 0
	.long 0
	.word 0
	.space 2
	.long __vt$filebuf
	.word 1
	.space 10
	.space  0x100		# For future use
.globl ___std_filebuf_2
	.align 2
___std_filebuf_2:
	.long -72499066
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long ___std_filebuf_1
	.long 0
	.long 0
	.long 0
	.long 0
	.word 0
	.space 2
	.long __vt$filebuf
	.word 2
	.space 10
	.space  0x100		# For future use
.globl _not_open_filebuf
	.align 2
_not_open_filebuf:
	.long -72499060
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.word 0
	.space 2
	.long __vt$filebuf
	.word -1
	.space 10
	.space  0x100		# For future use
.globl __9streambuf$_list_all
	.align 2
__9streambuf$_list_all:
	.long ___std_filebuf_2
