.TH "XHEXTRIS" 1 "06 April 1993"
.SH NAME
xhextris \- X Window hexagonal block dropping game
.SH SYNOPSIS
.B xtetris
[
.B "X options"
]
.SH DESCRIPTION
.I Xhextris
is a game involving dropping hexagonal blocks similar to xtetris.  You
can use the keyboard: j for moving to the left, l for moving to the
right, k to rotate clockwise, i to rotate counter-clockwise and space
for dropping quickly. The game is very similar to the tetris game. But
it does not many options.
.SH "ENVIRONMENT VARIABLES"
.IP XHEXNAME
If set, your desired name for the high score table.
.SH "COPYRIGHT"
Copyright 1990 David Markley, dm3e@+andrew.cmu.edu, dam@cs.cmu.edu
.SH AUTHORS
Daid Markley. Modified to use colors by Khun Yee Fung (clipper@csd.uwo.ca).
