.TH FAXENQ 8 "10 July 1991"
.SH NAME
faxenq \- enqueue a Group 3 fax job

.SH SYNOPSIS
.B faxenq phone1 phone2... [--- file1 file2...]
.RB [ " \-m" ]
.RB [ " \-u username" ]
.RB [ " \-h fax spooler host" ]

.SH DESCRIPTION
The
.B faxenq
commands enqueues a fax job to the spooler.  The fax will be delivered
to the one or more phone numbers specified after any options.  
Following the phone numbers, a list of Group 3 files can be specified.
If no files are given, the data for one Group 3 file is expected from
the standard input.

Filenames can have a special format of
.B name:number,
where
.B name
is a base filename, and
.B
number
is an integer.  A filename of this type is expanded to be the names
name.1, name.2, etc., until the given integer limit.

.SH OPTIONS
.LP
If no files are given, faxenq reads from the standard input.
.TP 14
.B \-m
Tells the system to mail you a notice when the fax has been delivered
to all recipients, or when the transmission has timed out.
.TP
.B \-u username
Specifies an alternative username for queuing the job.
.TP
.B \-h host
Specifies the host for the fax spooler.  The environment variable
FAXHOST can also be used to specify this host.

.SH SEE ALSO
fax(1), faxps(1), faxq(1), faxrm(1), faxspooler(8)
