.TH FAXMAIL 8 "10 July 1991"
.SH NAME
faxmail\- mailer interface for sending a fax

.SH SYNOPSIS
.B faxmail

.SH DESCRIPTION
The
.B faxmail
commands sends electronic documents as CCITT Group 3 faxes.  The input
to this program is assumed to be an electronic mail message.  Special
headers are used to specify the fax receipient and the coverpage
information.  The headers that this program recognizes are listed here:
.TP 15
.B Return-Path:
This field is used for the return address for delivery notification.
.TP
.B From:
The return address for delivery notification if a Return-Path header wasn't 
found.  In addition, the From field is used on the coversheet if a Sender
field isn't present.
.TP
.B Phone:
The fax phone number for sending the message.
.TP
.B Recipient:
This field is used for the recipient on the coversheet.
.TP
.B Sender:
This field is used for the sender on the coversheet.
.TP
.B Sender-Phone:
This field is used for the sender's return fax phone on the coversheet.
.TP
.B No-Cover:
If this field is present, a coversheet will not be sent.

.SH SEE ALSO
fax(1), faxps(1), faxq(1), faxrm(1), faxenq(8), faxspooler(8)
