.TH FAXQ 1 "10 July 1991"
.SH NAME
faxq \- list the fax spooler queue

.SH SYNOPSIS
.B faxq
.RB [ " \-h fax spooler host" ]

.SH DESCRIPTION
The
.B faxq
commands lists the fax spooler queue.

.SH OPTIONS
.TP 14
.B \-h host
Specifies the host for the fax spooler.  The environment variable
FAXHOST can also be used to specify this host.

.SH SEE ALSO
fax(1), faxps(1), faxrm(1), faxenq(8), faxspooler(8)
