.TH FAXRM 1 "10 July 1991"
.SH NAME
faxrm \- delete a job from the fax spooler queue

.SH SYNOPSIS
.B faxrm job
.RB [ " \-h fax spooler host" ]

.SH DESCRIPTION
The
.B faxrm
commands delete the given job from the fax spooler queue.  If the
job is in progress, it cannot be deleted until the delivery attempt
failes.

.SH OPTIONS
.TP 14
.B \-h host
Specifies the host for the fax spooler.  The environment variable
FAXHOST can also be used to specify this host.

.SH BUGS
There should be a way to cancel a job that is being delivered.

.SH SEE ALSO
fax(1), faxps(1), faxrm(1), faxq(1), faxenq(8), faxspooler(8)
