#!/depot/path/expect --
# rlogin.exp - rlogin but with same directory
#
# You can extend this idea to save any arbitrary information across rlogin
# Don Libes -  Oct 17, 1991.

set prompt "(%|#|\$) "		;# default prompt
if [info exists env(EXPECT_PROMPT)] {set prompt $env(EXPECT_PROMPT)}

eval spawn rlogin [lrange $argv 1 end]
set timeout 60
expect eof exit timeout {send_user "timed out\n"; exit} -re $prompt
send "cd [exec /bin/pwd]\r"
interact
