#!../expect -f
# read a complete line from stdin (minus terminating newline)
# aborting after the number of seconds (given as an argument)
# - Don Libes
set timeout [lindex $argv 1]
expect -re "(.*)\n" {send_user $expect_out(1,string)}
