#define ERR_CANVAS_TABLE_FULL 			 1
#define ERR_DELETION_OF_SCREEN 			 2
#define ERR_DELETION_OF_ACTIVE_CANVAS 		 3
#define ERR_ALREADY_ENABLED 			 4
#define ERR_NOT_ENABLED 			 5
#define ERR_BAD_RECT 				 6
#define ERR_BAD_FONT_INDEX 			 7
#define ERR_UNKNOWN_FONT   			 8
#define ERR_BAD_POLY_ITEM_COUNT 		 9
#define ERR_BAD_LINE_STYLE      		10
#define ERR_BAD_MARKER_STYLE 			11
#define ERR_BAD_WRITE_MODE 			12
#define ERR_BAD_PIXEL_VALUE			13
#define ERR_BAD_FILL_STYLE 			14
#define ERR_BAD_PATTERN_ID 			15
#define ERR_BAD_CURSOR_ID 			16
#define ERR_CANVAS_NOT_OPEN 			17
#define ERR_BAD_DEVICE				18
#define ERR_BAD_MODE				19
#define ERR_BAD_GET                             20
#define ERR_QUEUE_FULL                          21
#define ERR_BAD_LOC_ECHO_TYPE                   22
#define ERR_BAD_KEY_PROCESSING_MODE             23
#define ERR_POINTLIST_SIZE             	        24
#define ERR_BAD_FONT_FILENAME			25
#define ERR_MALLOC				26
#define ERR_NOT_IMPLEMENTED_YET			27
#define ERR_X_SERVER				28
#define ERR_BAD_LINE_WIDTH			29
#define ERR_BAD_PATTERN_TABLE_ENTRY		30
#define ERR_BAD_MARKER_SIZE			31
#define ERR_PATTERN_ALLOCATION		        32
#define ERR_BAD_COLOR_NAME			33
#define ERR_MAC_MISSING_RSRCS			34
