.TH mailto-hebrew 1 "Release 1"
.SH NAME
mailto-hebrew - Run the mailto program to send Hebrew/English mail
.SH SYNOPSIS
.ta 8n
\fBmailto-hebrew\fP  mailto-arguments
.br
.SH DESCRIPTION
The
.I mailto-hebrew
program will start an xterm using the appropriate font in order to send mail in mixed Hebrew and English.  All comand line options will be passed on to the mailto program.
.SH SEE ALSO
mailto(1), shownonascii(1)
.SH BUGS
This is such a tiny program it might actually be bug-free, but I wouldn't bet on it.
.SH COPYRIGHT
Copyright (c) 1991 Bell Communications Research, Inc. (Bellcore)

Permission to use, copy, modify, and distribute this material 
for any purpose and without fee is hereby granted, provided 
that the above copyright notice and this permission notice 
appear in all copies, and that the name of Bellcore not be 
used in advertising or publicity pertaining to this 
material without the specific, prior written permission 
of an authorized representative of Bellcore.  BELLCORE 
MAKES NO REPRESENTATIONS ABOUT THE ACCURACY OR SUITABILITY 
OF THIS MATERIAL FOR ANY PURPOSE.  IT IS PROVIDED "AS IS", 
WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES.
.SH AUTHOR
Nathaniel S. Borenstein, Bellcore
