Welcome, archive user!  This is an experimental FTP server.  If have any
unusual problems, please report them via e-mail to root@%L
If you do have problems, please try using a dash (-) as the first character
of your password -- this will turn off the continuation messages that may
be confusing your ftp client.

Local Time is %T.

You are user %N out of a maximum %M.

There is currently %FMBytes disk space on the archive.
