.TH setname 1L "July 25, 1989"
.SH NAME
setname \- name an MGR window
.SH SYNOPSIS
.B setname
\fIwindow name\fP
.SH DESCRIPTION
\fBsetname\fP sets the \fBNOTIFY\fP string of its window.  Programs like
\fBify(1L)\fP use the \fBNOTIFY\fP string as the 'name' of the window.
.PP
\fIWindow name\fP may contain % escapes, in the manner of
\fBprintf(3S)\fP.  \fBSetname\fP performs the following substitutions on
\fIwindow name\fP:
.TP
.B \fB%m\fP
replaced by the name of the machine \fBsetname\fP is running on
.TP
.B \fB%w\fP
replaced by the width of the window, in columns of text
.TP
.B \fB%c\fP
replaced by the height of the window, in rows of text
.TP
.B \fB%p\fP
replaced by a vague verbal description of the window's position
.TP
.B \fB%%\fP
replaced by a single \fB%\fP
.SH SEE ALSO
mgr(1L), ify(1L)
.SH DIAGNOSTICS
If \fBsetname\fP is invoked with no arguments, it prints a short explanatory
message.
.SH BUGS
Creeping featurism at its worst.  Real hackers use escape codes.
.SH AUTHOR
Jim Blandy
