#!/bin/sh
set -x

INSTALL=/usr/gnu/bin/install

$INSTALL -d -o bin -g bin ../MM/DIST
$INSTALL -d -o bin -g bin ../MM/DIST/usr
$INSTALL -d -o bin -g bin ../MM/DIST/usr/local
$INSTALL -d -o bin -g bin ../MM/DIST/usr/local/bin
$INSTALL -d -o bin -g bin ../MM/DIST/usr/local/doc
$INSTALL -d -o bin -g bin ../MM/DIST/usr/local/doc/mm
$INSTALL -d -o bin -g bin ../MM/DIST/usr/local/man
$INSTALL -d -o bin -g bin ../MM/DIST/usr/local/man/man.1

$INSTALL -o bin -g bin -m 0644 mm.overview ../MM/DIST/usr/local/doc/mm
$INSTALL -o bin -g bin -m 0644 README ../MM/DIST/usr/local/doc/mm


