#                        Copyright (c) 1988 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	$Header: Makefile,v 1.2 88/07/21 14:04:42 sau Exp $
#	$Source: /tmp/mgrsrc/icon/eye/RCS/Makefile,v $

#	eye icons for mgr
START=.
ICONS= \
	eye eye1 eye10 eye11 eye12 eye13 eye14 \
	eye15 eye16 eye17 eye18 eye19 eye2 eye20 \
	eye21 eye22 eye23 eye24 eye3 eye4 eye5 \
	eye6 eye7 eye8 eye9

all clean clobber cpio:

list:
	@for i in Makefile $(ICONS); do \
		echo "$(START)/$$i"; \
	 done
