.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH DOSHELL 8 "24 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
doshell \- Execute a program on a new tty
.SH SYNOPSIS
.B /etc/doshell
new_tty command
.SH DESCRIPTION
.B doshell
will close the current tty, open
.B new_tty
for standard input and output, and start
.BR command .
.B doshell
can be used to start a shell on an arbitrary tty, by using the command:
.I "doshell /etc/tty2 /etc/bash"
.SH "SEE ALSO"
.BR login (1),
.BR init (8),
.BR getty (8)
.SH BUGS
No diagnostics are printed, and no check on proper arguments is performed.
All arguments must have fully qualified pathnames.
.sp
In particular, no checking is performed to be sure that the first argument
is a device.  Therefore, if the arguments are accidentally reversed, a
binary can be trashed.
.SH AUTHOR
Jim Wiegand
