.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH FDISK 8 "24 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
fdisk \- Partition table manipulator for Linux
.SH SYNOPSIS
.B /etc/fdisk
.B "[ \-l ] [ \-v ] ["
device
.B ]
.SH DESCRIPTION
.B fdisk
is a menu driven program for manipulation of the hard disk partition table.
The
.I device
is usually one of the following:
.sp
.nf
.RS
/dev/hda
/dev/hdb
/dev/sda
/dev/sdb
.RE
.fi

The following commands are supported from the main menu:
.sp
.nf
.RS
a   toggle a bootable flag
d   delete a partition
l   list known partition types
m   print this menu
n   add a new partition
p   print the partition table
q   quit without saving changes
t   change a partition's system id
u   change display/entry units
v   verify the partition table
w   write table to disk and exit
x   extra functionality (experts only)
.RE
.fi

The following command are supported from the "extra functionality" menu:
.sp
.nf
.RS
b   move beginning of data in a partition
c   change number of cylinders
e   list extended partitions
h   change number of heads
m   print this menu
p   print the partition table
q   quit without saving changes
r   return to main menu
s   change number of sectors
w   write table to disk and exit
.RE
.fi

If possible,
.B fdisk
will obtain the disk geometry automatically.  This is
.I not
necessarily the
.I physical
disk geometry, but is the disk geometry that MS-DOS uses for the partition
table.  If
.B fdisk
warns you that you need to set the disk geometry, please believe this
statement, and set the geometry.  This should only be necessary with
certain SCSI host adapters (the drivers for which are rapidly being
modified to provide geometry information automatically).
.SH OPTIONS
.TP
.B \-v
Prints version number of
.B fdisk
program.
.TP
.B \-l
Lists the partition tables for
.B /dev/hda
and
.BR /dev/hdb ,
and then exits.  This isn't very helpful if you have SCSI drives.
.SH AUTHOR
A. V. Le Blanc (LeBlanc@mcc.ac.uk)
