.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH RDEV 8 "27 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
rdev \- query/set image root device, swap device, RAM disk size, or video mode
.SH SYNOPSIS
.nf
.BR "/etc/rdev [ \-rsv ] [ \-o " offset " ] [ " image " [ " value " [ " offset " ] ] ]"
.BR "/etc/rdev [ \-o " offset " ] [ " image " [ " root_device " [ " offset " ] ] ]"
.BR "/etc/swapdev [ \-o " offset " ] [ " image " [ " swap_device " [ " offset " ] ] ]"
.BR "/etc/ramsize [ \-o " offset " ] [ " image " [ " size " [ " offset " ] ] ]"
.BR "/etc/vidmode [ \-o " offset " ] [ " image " [ " mode " [ " offset " ] ] ]"
.fi
.SH DESCRIPTION
With no arguments,
.B rdev
outputs an
.I /etc/mtab
line for the current root file system.
With no arguments,
.BR swapdev , ramsize ", and " vidmode
print usage information.

In a bootable image for the Linux kernel, there are several pairs of bytes
which specify the root device, the video mode, the size of the RAM disk,
and the swap device.  These pairs of bytes, by default, begin at offset 508
(decimal) in the kernel image.
.B rdev
will change these values.

Typical values for the
.I image
parameter, which is a bootable Linux kernel image, are as follows:

.nf
.RS
/linux
/linux.test
/vmunix
/vmunix.test
/dev/fd0
/dev/fd1
.RE
.fi

When using the
.BR rdev ", or " swapdev
commands, the
.IR root_device or swap_device
parameter are as follows:

.nf
.RS
/dev/hda[1-8]
/dev/hdb[1-8]
/dev/sda[1-8]
/dev/sdb[1-8]
.RE
.fi

For the
.B ramsize
command, the
.B size
parameter specifies the size of the RAM disk in kilobytes.

For the
.B vidmode
command, the
.B mode
parameter specifies the video mode:

.nf
.RS
-3 = Prompt
-2 = Extended VGA
-1 = Normal VGA
 1 = as if "1" was pressed at the prompt
 2 = as if "2" was pressed at the prompt
 n = as if "n" was pressed at the prompt
.RE
.fi

If the
.I value
is not specified, the
.I image
will be examined to determine the current settings.

.SH BUGS
For historical reasons, there are two methods for specifying alternative
values for the offset.
.sp
The user interface is cumbersome, non-intuitive, and should probably be
re-written from scratch, allowing multiple kernel image parameters to be
changed or examined with a single command.
.SH AUTHORS
.nf
Originally by Werner Almesberger (almesber@nessie.cs.id.ethz.ch)
.br
Modified by Peter MacDonald

