.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH SYNC 8 "25 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
sync \- flush Linux filesystem buffers
.SH SYNOPSIS
.B /etc/sync
.SH DESCRIPTION
.B sync
executes
.BR sync (2),
which flushes the filesystem buffers to disk.
.B sync
should be called before the processor is halted in an unusual manner (i.e.,
before causing a kernel panic when debugging new kernel code).  In general,
the processor should be halted using the
.BR reboot "(8), or " halt (8)
commands, which will attempt to put the system in a quiescent state before
calling
.BR sync (2).
.SH "SEE ALSO"
.BR sync (2),
.BR update (8),
.BR reboot (8),
.BR halt (8)
.SH AUTHOR
Linus Torvalds (torvalds@cs.helsinki.fi)
