.\" Copyright 1992 Rickard E. Faith (faith@cs.unc.edu)
.\" May be distributed under the GNU General Public License
.TH UPDATE 8 "25 December 1992" "Linux 0.98" "Linux Programmer's Manual"
.SH NAME
update \- periodically flush Linux filesystem buffers
.SH SYNOPSIS
.B /etc/update
&
.SH DESCRIPTION
.B update
executes
.BR sync (2)
every 30 seconds.  It is generally started at boot time in
.IR /etc/rc .
.SH "SEE ALSO"
.BR sync (2),
.BR sync (8),
.BR init (8)
.SH AUTHOR
Linus Torvalds (torvalds@cs.helsinki.fi)
