.TH TEXMGR l
.SH NAME
texmgr \- tex previewer for mgr
.SH SYNOPSIS
.B "texmgr [-fn] [-mn] [-bn] [-dn] [-sddd] name"
.LP
.B "texmgr -V"
.SH DESCRIPTION
.I texmgr
will read a tex dvi file and display it in a MGR window.   
Texmgr was derived from the 3b1 previewer, tex3b1.   Both previewers do
subsampling of glyphs (shrinking) so that you can use fonts of higher
resolution than the screen itself.  This means only one set of fonts (the
printer fonts) are needed.
.PP
Texmgr reads /usr/local/lib/tex/fontdesc
to find the directory where font files are stored.
You can use any combination of pk, gf and pxl font files.
In addition, the choice to make boxes or leave blanks when missing
fonts are encountered is controlled by this file, based on
information from the tfm file.
.PP
Since the MGR display on the 3b1 is just 720 x 348 pixels in size, texmgr can
generally display only a partial page at a time.  Therefore, commands
exist to move the page around on the screen as well as to select a
new page to view.
.PP
Texmgr potentially displays each partial page in three possible 
magnifications (really "shrinkages").  These three shrink values
allow users to zoom in (a small shrink value) or zoom out (a large
shrink values) as a dvi file is being previewed. 
.SH OPTIONS
.IP V
Just print the version number of the current texmgr and a usage
statement.  No previewing is done.
.IP b 
[-b n] selects the blacker value.  The current default is 3, if your 
fonts are already thick then you might get by with a smaller number.
You may want
a larger number on MGR to make up for otherwise dropped pixels due
to subsampling during shrinking of glyphs.
.IP f 
[-f n] selects the starting page for texmgr to display.
This page number is strictly the count from the start of the dvi file
and not the page number that TeX places at the bottom of the file.
.IP m 
[-m n] chooses which of the shrink values (there are three) to
make the default.  For instance, suppose shrink values are 2,3,5 
(or 235 as a shrink triple) then saying -m 3 would select 1/5 (shrink
value 5) as the default magnification.  Normally the largest readable
shrink value is placed first in the list since the default for 'm'
is 1.
.IP d 
[-d n] changes the dots per inch (dpi) font value.  Normally one
would recompile the code with the right value for their own system,
but if that is not possible then ``-d 240'' will allow you to run with
fonts built at 240 dpi.
.IP s 
[-s ddd] changes the default shrink values.  These values are
displayed in the middle button magnification menu.  Changing
from one magnification to another is equivalent to selecting one of
these three values.  For some types of work or for some font sizes it
makes sense to be able to control these shrink values. ``-s 482'', for
example, might give you a reasonable view of the page for a default
(shrink of 4) while allowing you to zoom out (shrink of 8) and zoom
in (shrink of 2) using the interactive commands 'm' and 'M' or the
magnification menu. 
.IP
Note that, for most printers, the screen pixels are much larger
and hence a shrink value of 1 (full resolution) will look very much
larger on the screen.  This 3-tuple method of naming three individual
numbers is a bit strange and limits you to values from 1 to 9.  For
very high resolution devices (linotype machines?) this may be too
limiting.  Most 3b1 owners with MGR, however, won't need to shrink more than 9.
.SH COMMANDS
Interactive commands:
.IP ?
Displays a summary of these interactive commands.
.PP
Screen movement commands:
.IP h
Move viewport a bit to the left.
.IP j
Move viewport a bit to the right.
.IP k
Move viewport a bit up.
.IP l
Move viewport a bit down.
.IP H
Move viewport completely to the left.  (X coordinate goes to 0.)
.IP J
Move viewport completely to the right.  (Left Margin is completely visible.)
.IP K
Move viewport to the top of the page. (Y coordinate goes to 0.)
.IP L
Move viewport to the bottom of the page. 
.IP <ff>,r
Either '^L' or 'r' reset the current page (X and Y coordinates back
to 0, same as 'H' then 'K').
.PP
Commands to move to different pages:
.IP <space>,f,n,<nl>,<cr>
\' ', 'f', 'n', '^J', and '^M' all move to next page.  A number preceding
any of the above will move forward that many pages (default is one).
.IP b,p,<bs>,<del>
\'b', 'p', '^H', and '^?' all move to the previous page.  A number preceding
any of the above will move backward that many pages (default is one).
.IP <n>g,<n>G
A number followed by g or G will go to the requested page: ``21G''.
Note the syntax may seem backwards, but it is easy to parse.  Just
think ``less'' and ``vi'' here.  The default page number is one.
.PP
Other interactive commands:
.IP m
Toggle between the first and second shrink value.  If shrink values
are 482, for instance, then the first 'm' will create a small 1/8
font display.  The next 'm' toggles back to 1/4 font display.
.IP M
Toggle between the current (or first) and third shrink value.  In
the example above, 'M' would give the largest magnification of the
page.  Once these magnifications have been computed for a page,
moving between one and another is relatively fast.
.IP R
Re-open the dvi file.  This generally isn't necessary.
.IP q,x,^C,^D
All these options leave texmgr.
.SH MOUSE
You can choose different magnifications with the menu
that is activated with the middle mouse button.
.PP
If you press the right mouse button, the location pointed
to by the arrow is placed as close to the
center of the screen as possible.   Placing the arrow slightly above
and left of center, and hitting the right button a number of times
will move you diagonally through the page at the current magnification.
.PP
A rule of thumb that seems to work for me is to make gross motions with
the keyboard (hjkl and HJKL) and fine selections with the mouse.  Indeed,
the only way to select exactly that section of the page you want on the
screen is to use the mouse.
.SH BUGS
Very low resolution fonts (like the ones Emmett Gray sent along with one of the
first TeX ports to the 3b1) don't seem to work very well.  This shouldn't
be a problem as most pinwriter and laser printer fonts are large enough
to work.
.SH AUTHOR
The code is based on texsun, which was written by Dirk Grunwald.
It uses Chris Torek's dvi library.  The 3b1 
port is by Andy Fyfe andy@csvax.caltech.edu.  The port to
MGR on the 3b1 is by Ross A. Jekel, s83949@ursa.calvin.edu until
August 1991 (after that at some graduate school).
.SH FILES
/usr/local/lib/tex/fontdesc
.br
and all the pk, gf, pxl and tfm files pointed to therein.
.SH THINGS TO IMPROVE
This was really just a simple rewrite and is rather slow
because it downloads the raster for a character every time
it is used.  I will be working on a version that will download
a character to a scratch bitmap the first time it is used and
then do bitmap to bitmap operations, which should go much faster.
.SH SEE ALSO
tex(1), latex(1), dvi2printer(1) (your dvi print driver), mf(1)
