.TH "CLISP SOURCE" 1 "2 March 1993"


.SH ABOUT
The source files for CLISP.


.SH FILE TYPES

.TP
.B *.d
The source files for unpreprocessed C code.

.TP
.B *.c
The C code after preprocessing.
They depend on the preprocessor: ansidecl or traddecl.

.TP
.B *.lsp
The source files for lisp code.

.TP
.B *.fas
Compiled lisp code. Depends on the machine on which CLISP runs and (perhaps)
on the compiler used to build CLISP.


.SH FILES

.TP
Unpreprocessed C code:
.RS 4

.TP
Includes:

.RS 4
.TP 15
.B lispbibl.d
main include file
.TP 15
.B fsubr.d
list of all built-in special forms
.TP 15
.B subr.d
list of all built-in functions
.TP 15
.B pseudofun.d
list of all "pseudo functions"
.TP 15
.B constsym.d
list of symbols accessed by C code
.TP 15
.B constobj.d
list of miscellaneous objects accessed by C code
.TP 15
.B unix.d
include file for unix implementations
.TP 15
.B atari.d
include file for Atari/TOS version
.TP 15
.B amiga.d
include file for Amiga/AmigaOS version
.TP 15
.B amiga2.d
second include file for Amiga/AmigaOS version
.TP 15
.B msdos.d
include file for MS-DOS or OS/2 based versions
.TP 15
.B vms.d
include file for VAX/VMS version
.RE

.TP
Modules:
.RS 4
.TP 15
.B spvw.d
Memory management (garbage collection), startup. some OS interface.
.RS 4
.TP 11
.B avl.d
An implementation of AVL trees.
.TP 11
.B sort.d
A sorting routine.
.RE
.TP 15
.B spvwtabf.d
Table of built-in special forms and functions.
.TP 15
.B spvwtabs.d
Table of symbols accessed by C code.
.TP 15
.B spvwtabo.d
Table of miscellaneous objects accessed by C code.
.TP 15
.B eval.d
Evaluator (form interpreter) and bytecode interpreter.
.TP 15
.B control.d
Special forms (form interpreter).
.TP 15
.B pathname.d
Pathnames, file- and directory-related functions.
.TP 15
.B stream.d
Streams of all kinds: file streams, terminal stream, string streams etc.
.TP 15
.B socket.d
Opening sockets for CLX.
.TP 15
.B io.d
The lisp reader (parser) and printer (also pretty printer).
.TP 15
.B array.d
Functions dealing with arrays and vectors.
.TP 15
.B hashtabl.d
Functions dealing with hash tables.
.TP 15
.B list.d
Functions dealing with lists.
.TP 15
.B package.d
Functions dealing with packages.
.TP 15
.B record.d
Functions dealing with records (structures, closures, etc.)
.TP 15
.B sequence.d
The generic sequence functions.
.TP 15
.B charstrg.d
Functions dealing with characters and strings.
.TP 15
.B debug.d
Support for debugging and the read-eval-print loop.
.TP 15
.B misc.d
Miscellaneous functions, error signalling.
.TP 15
.B predtype.d
Predicates, type tests.
.TP 15
.B symbol.d
Functions dealing with symbols.
.TP 15
.B vmsaux.d
Auxiliary functions (VAX/VMS version only).
.TP 15
.B rexx.d
Low-level Rexx interface (Amiga version only).
.TP 15
.B lisparit0.d
Functions dealing with numbers (arithmetic).
.TP 15
.B noreadline.d
Replacement for GNU readline library.
.TP 15
.B dbxtypes.d
Declaration of types for use with SUN's dbx (Sun version only).
.TP 15
.B alglobal.d
Declaration of all global variables of the library (Atari TOS version only).
.TP 15
.B main.d
Declaration of auxiliary functions for use with Gcc 2.
.RE

.TP 4
Number system (arithmetic):
.RS 4
.TP 15
.B lisparit.d
initialization, input/output of numbers, lisp functions
.TP 15
.B aridecl.d
declarations
.TP 15
.B arilev0.d
arithmetic at the machine level
.TP 15
.B arilev1.d
digit sequences
.TP 15
.B arilev1c.d
operations on digit sequences, written in C
.TP 15
.B arilev1i.d
operations on digit sequences, as inline functions
.TP 15
.B arilev1e.d
operations on digit sequences, bindings to external routines
.TP 15
.B intelem.d
integers: elementary operations
.TP 15
.B intlog.d
integers: logical connectives
.TP 15
.B intplus.d
integers: addition and subtraction
.TP 15
.B intcomp.d
integers: comparison
.TP 15
.B intbyte.d
integers: byte operations
.IR ldb ", " load-byte ", ..."
.TP 15
.B intmal.d
integers: multiplication
.TP 15
.B intdiv.d
integers: division
.TP 15
.B intgcd.d
integers: gcd and lcm
.TP 15
.B int2adic.d
integers: operations on 2-adic integers
.TP 15
.B intsqrt.d
integers: square root, n-th root
.TP 15
.B intprint.d
subroutines for integer output
.TP 15
.B intread.d
subroutines for integer input
.TP 15
.B rational.d
rational numbers
.TP 15
.B sfloat.d
elementary operations for short floats
.TP 15
.B ffloat.d
elementary operations for single floats
.TP 15
.B dfloat.d
elementary operations for double floats
.TP 15
.B lfloat.d
elementary operations for long floats
.TP 15
.B flo_konv.d
conversions between floats
.TP 15
.B flo_rest.d
general float operations
.TP 15
.B realelem.d
elementary functions for real numbers
.TP 15
.B realrand.d
random numbers
.TP 15
.B realtran.d
transcendental functions for real numbers
.TP 15
.B compelem.d
elementary functions for complex numbers
.TP 15
.B comptran.d
transcendental functions for complex numbers
.RE

.TP 4
External routines for the arithmetic system, written in assembly language:
.RS 4
.TP 20
.B ari68000.mit.d
written in 68000 assembler, MIT syntax
.TP 20
.B ari68000.mot.d
written in 68000 assembler, Motorola syntax
.TP 20
.B ari68000.atari.d
written in 68000 assembler, MIT syntax, use this for Atari version
.TP 20
.B ari68020.mit.d
written in 68020 assembler, MIT syntax
.TP 20
.B ari68020.mot.d
written in 68020 assembler, Motorola syntax
.TP 20
.B arisparc.d
written in SPARC assembler
.TP 20
.B ari80386.d
written in i386/i486 assembler
.TP 20
.B arimips.d
written in MIPS assembler
.TP 20
.B arihppa.d
written in HPPA-1.0 assembler
.TP 20
.B arivax.d
written in VAX assembler
.RE

.TP 4
External routines for accessing the stack, written in assembly language:
.RS 4
.TP 20
.B sp68000.mit.d
written in 68000 assembler, MIT syntax
.TP 20
.B sp68000.mot.d
written in 68000 assembler, Motorola syntax
.TP 20
.B spsparc.d
written in SPARC assembler
.TP 20
.B sp80386.d
written in i386/i486 assembler
.TP 20
.B spmips.d
written in MIPS assembler
.RE

.RE

.TP
Other assembly language stuff:
.RS 4
.TP
.B cc_sparc.il
lisp stack access in SPARC assembler, for use with Sun's cc
.RE

.TP
Lisp source files:

.RS 4
.TP
.B init.lsp
first file to be loaded, loads everything else
.TP
.B defseq.lsp
defines the usual sequence types for the generic sequence functions
.TP
.B backquot.lsp
implements the backquote read macro
.TP
.B defmacro.lsp
implements
.I defmacro
.TP
.B macros1.lsp
the most important macros
.TP
.B macros2.lsp
some other macros
.TP
.B defs1.lsp
miscellaneaous definitions
.TP
.B places.lsp
macros using places, definitions of most places
.TP
.B floatpri.lsp
printing floating point numbers in base 10
.TP
.B type.lsp
functions working with type specifiers:
.IR typep ", " subtypep
.TP
.B defstruc.lsp
implements the
.I defstruct
macro
.TP
.B format.lsp
implements
.I format
.TP
.B user1.lsp
user interface, from the system's point of view
.TP
.B user2.lsp
user interface, from the user's point of view
.TP
.B trace.lsp
tracer
.TP
.B macros3.lsp
(optional) the macros
.IR letf ", " letf* " and " nth-value .
.TP
.B config.lsp
(user written) site-dependent configuration,
may be a link to one of the following:
.RS
.TP 15
.B cfglinux.lsp
for Unix, using Linux
.TP 15
.B cfgsunux.lsp
for Unix, using SunOS
.TP 15
.B cfgunix.lsp
for any other Unix
.TP 15
.B cfgvms.lsp
for VMS
.TP 15
.B cfgatfd.lsp
for Atari, using floppy disk A:
.TP 15
.B cfgathd.lsp
for Atari, using hard disk E:
.TP 15
.B cfgamiga.lsp
for Amiga
.TP 15
.B cfgdos.lsp
for MS-DOS version
.RE
.TP
.B compiler.lsp
compiles lisp code to bytecode
.TP
.B rexx.lsp
for Amiga, an interface to Rexx
.TP
.B editor.lsp
(optional) the screen editor
.RE

.TP
Documentation:

.RS 4
.TP
.B FILES
lists the source files
.TP
.B FILES.1
nroff master for
.I FILES
.TP
.B _README
master for the distribution's README
.TP
.B _clisp.1
master for the distribution's manual page
.TP
.B _impnotes.txt
master for the distribution's implementation notes
.RE

.TP
Automatic configuration on Unix:

.RS 4
.TP
.B configure.in
lists the features to be checked
.TP
.B usr.local.lib.aclocal.m4
a repertoire of features. Use with GNU autoconf-1,2,
install as /usr/local/lib/aclocal.m4
.TP
.B configure
configuration script, checks for dozens of features
.TP
.B machine.d
figures out some machine parameters (word size, endianness etc.)
.TP
.B machine.c
preprocessed version of
.I machine.d
.TP
.B unixconf.h.in
header file master. unixconf.h contains the values of the features
found out by configure.
.TP
.B makemake.in
makefile construction script master
.RE
