.TH NFSD 8 "Jan 23, 1993"
.SH NAME
nfsd \- NFS service daemon
.SH SYNOPSIS
.nf
.B /etc/nfsd [-f exports-file] [-p] [-o option-string]
.fi
.SH DESCRIPTION
.I nfsd
starts a
daemon that handles client filesystem requests.
Unlike nfsd on some other systems,
nfsd operates as a normal user-level process.
The server also differs from other nfsd implementations
in that it mounts an entire file hierarchy
not limited by the boundaries of physical file-systems.
The implementation allows the clients read-only or
read-write access to the file hierarchy of the server machine.
.LP
.I mountd
starts
an ancillary user-level mount daemon.
.LP
.IR Options .
The
.B -f
option specifies the exports file, listing the clients that this server
is prepared to serve and parameters to apply to each such mount (see
exports(5)).
By default exports are read from
.IR /etc/exports .
The
.B -p
option puts the server into promiscuous mode where it will serve any host
on the network.
The
.B -o
option specifies default mount parameters in the same format as those appearing
in the
.I exports
file.
.SH "SEE ALSO"
exports(5), mountd(8), ugidd(8C)
.SH AUTHORS
Mark Shand wrote the orignal unfsd.
Don Becker extended unfsd to support authentication
and allow read-write access and called it hnfs.
Rick Sladkey added host matching, showmount -e support,
mountd authentication, and inetd support.
