.\" Copyright 1993 Rick Sladkey <jrs@world.std.com>
.\" May be distributed under the GNU General Public License
.TH SHOWMOUNT 8 "11 April 1993" "Linux 0.99" "Linux Programmer's Manual"
.SH NAME
showmount \- show mount information for an NFS server
.SH SYNOPSIS
.B /etc/showmount
.B "[ \-aedh ]"
.B "[ host ]"
.SH DESCRIPTION
.B showmount
queries the mount daemon on a remote host for information about
the state of the NFS server on that machine.  With no options
.B showmount
lists the set of clients who are mounting from that host.
The output from
.B showmount
is designed to
appear as though it were processesed through ``sort -u''.
.SH OPTIONS
.TP
.B \-a
List both the client hostname and mounted directory in
host:dir format.
.TP
.B \-d
List only the directories mounted by some client.
.TP
.B \-e
Show the NFS server's export list.
.TP
.B \-h
Suppress the decriptive headings from the output.
.SH "SEE ALSO"
.BR mountd (8),
.BR nfsd (8)
.SH BUGS
The completeness and accurary of the information that
.B showmount
displays varies according to the NFS server's implementation.
.P
Because
.B showmount
sorts and uniqs the output, it is impossible to determine from
the output whether a client is mounting the same directory more than once.
.SH AUTHOR
Rick Sladkey <jrs@world.std.com>
