#
#       @(#)Makefile.customer 1.5 90/06/21 
#
#	Makefile for the cursor example programs for XView programmers
#

INCLUDE 	= -I${OPENWINHOME}/include

#
# If you want to compile for debugging, change "-O" to "-g"
#

CFLAGS		= ${INCLUDE} -O

# if you want special to pass special loader options to ld, set
# LDFLAGS= ...
#

XVIEW_LIBS	=  -L${OPENWINHOME}/lib \
		   -lxview -lolgx -lX11

CFILES		= hot_spot.c \
		  simple_cursor.c \
		  stop_cursor.c
	   
OBJS		= hot_spot \
		  simple_cursor \
		  stop_cursor

all:   ${OBJS}

${OBJS}: $$@.c $$@.o 
	${CC} ${CFLAGS} ${LDFLAGS} -o $@ $@.o ${XVIEW_LIBS}

clean:
	rm -f core ${OBJS} *.o
