.TH mgrload 1 "October 24, 1992"
.SH NAME
mgrload -\ Graph of system load average
.SH SYNOPSIS
.B mgrload
.SH DESCRIPTION
.I Mgrload
displays the current CPU load, which is defined as a floating point number
greater than or equal to zero and represents the average number of processes
which were on the run queue during the past 60 seconds.
.I Mgrload 
represents this data as a scrolling bar graph with each bar
representing the load during a 60 second interval.  The vertical scale of
the graph is dynamically adjusted to account for changing load average
values.  Horizontal lines are placed on the graph spaced at a value
of 0.50 apart.  Precise values for the displayed maximum, minimum and most
recent load value can be shown using the menu available when the right
mouse button is pressed.  System information such as the host name is
available by pressing the middle mouse button.  This information can be
useful when
.I mgrload
is run in a networked environment and several
.I mgrloads
are running to display load averages of remote systems.
Additional funtions such as redrawing the graph and resetting all stored
values are also available by pressing the right mouse button.
.SH AUTHOR
Mark Dapoz <mdapoz%hybrid@cs.toronto.edu>
Michael Haardt
