.TH xmix 1 "12 June 1992"
.IX xmix
.SH NAME
xmix - X Windows interface to the Sound Blaster Pro audio mixer
.SH SYNOPSIS
.B xmix 
.RI [options]
.SH DESCRIPTION

This is my first attempt at a graphical interface to the Sound Blaster mixer.
Just play with it a little, and I hope it's all self explanatory.
Future versions may include a complete man page.

Note that you must load the XMix Resource file into your resource
database before running xmix, or else there will be no colors, and too
many borders.  A typical command to load the resources is:

.B xrdb XMix

Alternatively, you could install the XMix file in your local
app-defaults directory (typically /usr/X11/lib/app-defaults).

.SH OPTIONS
.PP
This application uses all standards X Toolkit options.

.SH BUGS
None known.
.SH SEE ALSO
mixer(1)
.SH AUTHOR
Steve Haehnichen <shaehnic@ucsd.edu>
