.TH shrink_map 1L "November 30, 1990"
.SH NAME
Shrink_map \- Shrink a  MGR bitmap to 1/2 size.
.SH SYNOPSIS
< image shrink_map <thresh>  > image.small
.SH DESCRIPTION
Shrink_map reads an MGR (1 bit per pixel) bitmap from
standard input, shrinks it in half, and writes the result to sandard output.
The 
.I thres
argument is used to specify how many in each group of 4 pixels need to
be set before the corrosponding output pixel is set.
.SH BUGS
.TP
*
The algorithm was intended for reducing many images at once, and is
inefficient when dealing with one image at a time.
.SH SEE ALSO
mgr(1L)
bitmap(4L)
.SH AUTHOR
S. A. Uhler
