.TH shrink 1L "November 30, 1990"
.SH NAME
Shrink \- Shrink a $HOME MOVIE script to play back in 1/2 the
size.
.SH SYNOPSIS
< script shrink  | play_data -
.SH DESCRIPTION
Shrink reads a $HOME MOVIE binary script on standard input, then writes a
shrunk version on standard output.
.SH BUGS
.TP
*
Some loss of resolution results from shrinking the bitmap images.
.TP
*
Sometimes inconsistent rounding causes image tearing.
.SH SEE ALSO
mgr(1L)
movie(1L)
play_data(1L)
.SH AUTHOR
S. A. Uhler
