.TH time_it 1L "November 30, 1990"
.SH NAME
time_it \- Time the sections of a $HOME MOVIE
size.
.SH SYNOPSIS
time_it <files...>
.SH DESCRIPTION
time_it reads binary or compressed binary $HOME movie scripts and
displays the timeing information for each section.
.SH BUGS
.TP
*
time_it, a shell script is vert slow.
.TP
*
time_it doesn't understand timing marks.
.SH FILES
zcat(1) to_ascii(1L)
.SH SEE ALSO
movie(1L)
play_data(1L)
time_au(1L)
.SH AUTHOR
S. A. Uhler
