.TH to_ascii 1L "April 30, 1990"
.SH NAME
to_ascii \- Convert a $HOME MOVIE video script to ASCII format.
.SH SYNOPSIS
to_ascii [-x]
.SH DESCRIPTION
To_ascii converts a $HOME MOVIE video script into an ASCII format.
Each video script command is printed on a single line.  The first character, in the
set of "B D K L M P S T W" represent Bitblts, Data, Kill-image, Line, Mark, 
Point, Screen-size, Time, and Write-only bitblt.
The Command letter is followed by the numerical data for that command.
In the case of
.I Data ,
which represents image data, the succeeding lines starting with "." contain
a hexidecimal representation of the data for the image.  If the 
.I -x
flag is used, the image data is supressed.
.SH SEE ALSO
mgr(1L)
play_data(1L)
to_binary(1L)
.SH AUTHOR
S. A. Uhler
