.\"
.\" selection.1 - the cut and paste utility for Linux virtual consoles
.\"
.TH selection 1 "Dec 14, 1992"
.SH NAME
selection - the cut and paste utility for Linux virtual consoles
.SH SYNTAX
\fBselection\fR
.SH DESCRIPTION
\fBselection\fR is a utility that allows characters to be selected from the
current Linux virtual console using the mouse and pasted into the current
console. \fBselection\fR is normally invoked at boot time from /etc/rc.local,
and runs as a background process.
.PP
To invoke the selection mechanism, press and release the left mouse button
(the meaning of the left and right-hand buttons may be reversed at compile
time; consult the installation notes). A highlighted block will start
moving around the screen, correlated with the movement of the mouse.
.PP
Move the block to the first character of the selection, then press and hold
down the left mouse button.
.PP
Drag out the selection; the selected text will be highlighted. Then release
the left button. You can take the end of the selection to before the start of
the selection if necessary.
.PP
Double-clicking the left-hand button while the highlighted block is on the
screen selects text by word boundaries; treble-clicking selects by entire
lines. If the button is held down after double- or treble-clicking, multiple
words or lines may be selected. A word consists of a set of alphanumeric
characters and underscores.
.PP
If a trailing space after the contents of a line is highlighted, and if there
is no other text on the remainder of the line, the rest of the line will be
selected automatically. If a number of lines are selected, highlighted
trailing spaces on each line will be removed from the selection buffer.
.PP
Pressing the right-hand mouse button in any virtual console pastes the
selected text into the read queue of the associated tty.
.PP
Any output on the virtual console holding the selection will clear the
highlighted selection from the screen, to maintain integrity of the display,
although the contents of the paste buffer will be unaffected.
.PP
The selection mechanism is disabled if the controlling virtual console is
placed in graphics mode, for example when running X11, and is re-enabled when
text mode is resumed.
.SH FILES
/dev/mouse - mouse device
.br
/dev/tty0 - current VC device
.SH DIAGNOSTICS
\fBselection\fR complains if the devices it requires cannot be located.
.SH BUGS
The size of the paste buffer is set at 2048 bytes by default. This may be
changed at compile time; consult the installation notes.
.PP
The selection mechanism doesn't work very well with graphics characters, or
indeed with any characters where a mapping between the typed character and
the displayed character is performed by the console driver. The selection
mechanism pastes into the input buffer the character codes as they are
displayed on the screen, not those originally typed in by the user.
.SH AUTHOR
.nf
Andrew Haylett <ajh@gec-mrc.co.uk>
.SH ACKNOWLEDGEMENTS
.nf
Lefty patches from Sotiris C. Vassilopoulos <scv2f@edu.Virginia.acc.honi4>
.br
Logitech patches from Jim Winstead Jr <jwinstea@jarthur.Claremont.EDU>
