.TH TEXT2FONT 1 "5 November 1992"
.SH NAME
text2font, font2text \- convert between MGR font format and text
.SH SYNOPSIS
.B text2font
<file.txt >file.fnt
.br
.B font2text
<file.fnt >file.txt
.SH AVAILABILITY
.PP
.B text2font
is available by anonymous FTP to
.B ftp.lysator.liu.se
in file
.B /pub/mgr/text2font.tar.Z.
The program is in the public domain.
Use it at your own risk.
MGR is a window manager by Steven Uhler at Bellcore.
.SH DESCRIPTION
.PP
.B text2font
reads a text file representing an MGR font from standard input.
It writes the binary MGR font file to standard output.
.B font2text
performs the exact inverse of this operation.
If you convert your favorite MGR font to text,
you can edit it with your favorite text editor,
and then convert it back to a font file.
This is a poor man's font editor.
.PP
The text format is very special,
and text files can easily be corrupted beyond recognition.
Be careful.
.PP
At the top of the file,
six decimal values appear separated by white space.
These represent, in turn, the
.B type,
.B width,
.B height,
.B base
line
offset,
character
.B count,
and
.B start
character
of the font.
The meaning of these parameters are described below,
but also in the description of the MGR font format
in man page
.B font(5).
.PP
Then follows the layout for all characters,
one character at a time.
The first character will have character value
.B start,
which is typically 0 (for NUL) or 32 (for space).
There should be exactly
.B count
characters in the file.
Each character is represented by
.B height
rows of
.B width
bits each.
Each bit is either a one (an asterisk *) or a zero (a dot .).
.PP
When converting from this text format to the MGR font file,
all other characters, including white space and letters,
are ignored. The total number of bits must be exact,
or else
.B text2font
will complain.
.PP
Each character has its base line
.B base
positions from the bottom.
This is noted, so that MGR will know where to put an underline cursor.
.SH SEE ALSO
mgr(1), font(5)
.SH AUTHOR
.B text2font
was written by Lars Aronsson, Lysator, Linkoping, Sweden
<aronsson@lysator.liu.se>.
Let me know what you think of these programs,
but beware! You use them at your own risk!
The programs are in the public domain.
