"======================================================================
|
| Copyright (C) 1990, 1991 Free Software Foundation, Inc.
| Written by Steve Byrne.
|
| This file is part of GNU Smalltalk.
|
| GNU Smalltalk is free software; you can redistribute it and/or modify it
| under the terms of the GNU General Public License as published by the Free
| Software Foundation; either version 1, or (at your option) any later version.
| 
| GNU Smalltalk is distributed in the hope that it will be useful, but WITHOUT
| ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
| FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
| details.
| 
| You should have received a copy of the GNU General Public License along with
| GNU Smalltalk; see the file LICENSE.  If not, write to the Free Software
| Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.  
|
 ======================================================================"



Object variableByteSubclass: #Host
       instanceVariableNames: ''
       classVariableNames: ''
       poolDictionaries: ''
       category: nil!

Host comment: 
'I provide a mechanism to talk about Internet hosts.  My instances can be
created by either the host name or the dotted, 4 octet address notation.
I should be able to provide some form of connection to the named
remote host, but that isn''t implemented at this time.' !

Host inspect!

"### NOT IMPLEMENTED YET###"
