.\" This file Copyright 1992 Robert J. Nation 
.\" (nation@rocket.sanders.lockheed.com)
.\" It may be distributed under the GNU Public License, version 2, or
.\" any higher version.  See section COPYING of the GNU Public license
.\" for conditions under which this file may be redistributed.
.TH TOP 1 "Feb 1 1993" "Linux" "Linux Programmer's Manual"
.SH NAME
top \- display top CPU processes
.SH SYNOPSIS
top
.SH DESCRIPTION
.B "top "
provides an ongoing look at processor activity. At any time, top displays
CPU activity since the last update.
This man page documents the /proc-based version of top, or tries to.
.PP
.SH "COMMAND\-LINE OPTIONS"
There are no command line arguments to top at this time.

.SH "FIELD DESCRIPTIONS"
Top displays a variety of information about the processor state. The display is
updated every 5 seconds by default.
.TP 0.5i
.B "load averages "
This line displays the three load averages for the system. Unfortunately,
I don't really know what load averages are, except that they are a measure
of CPU load.
.TP 0.5i
.B "processes "
The total number of processes running at the time of the last
update. Also breaks this down into the number of tasks which are
running, sleeping, stopped, or zombies.
.TP 0.5i
.B "CPU states "
Shows the percentage of CPU time in user mode, system mode, running
niced tasks, and idle. Note that niced tasks are only those whose nice 
value is negative. Also time spent in niced tasks will also be counted 
in either system or user time, so the total will appear to be more than 100%.
.TP 0.5i
.B "Mem "
Displays memory usage, including total available memory, free memory, used memory, shared memory, and memory used for buffers.
.TP 0.5i
.B "Swap "
Shows statistics for swap space, including total swap space, available swap space, and used swap space.
.TP 0.5i
.B "PID "
The process ID of each task which is running is shown in this column.
.TP 0.5i
.B "USER "
The user name of the task's owner is shown in this column
.TP 0.5i
.B "PRI "
The priority of the task is shown here
.TP 0.5i
.B "NI "
The nice value of the task is shown here. Negative nice values are lower
priority.
.TP 0.5i
.B "SIZE "
The size of the task's code plus data plus stack space, in kilobytes,
is shown here.
.TP 0.5i
.B "RSS "
The total amount of physical memory used by the task, in kilobtes, is shown 
here.
.TP 0.5i
.B "SHRD "
The amount of shared memory used by the task is shown in this column.
.TP 0.5i
.B "ST "
The state of the task is shown here. The state is either S for sleeping,
D for uninterruptible sleep, R for running, Z for zombies, or T for stopped or
traced.
.TP 0.5i
.B "TIME "
The task's CPU time since it started is shown here.
.TP 0.5i
.B "%CPU "
The task's share of the CPU time since the last screen update is shown in this 
column. This is expressed as a percentage of total CPU time.
.TP 0.5i
.B "%MEM "
The task's share of the physical memory is shown here.
.TP 0.5i
.B "COMMAND "
The task's command name is shown here.

.SH INTERACTIVE COMMANDS
Several single key commands are recognized while top is running.
.TP 0.5i
.B "h" 
This causes a help screen to be displayed.
.TP 0.5i
.B "?"
Same as h.
.TP 0.5i
.B q
Quit
.TP 0.5i
.B n
Change the number of processes to show. You will be prompted to enter the 
number. This over-rides automatic determination of the number of processes 
to show, which is based window size measurement. If n is not specified, 
then top will show as many processes as will fit on the screen.
.TP 0.5i
.B #
Same as n.
.TP 0.5i
.B k
Kill a process. You will be prompted for the PID of the task, and the signal 
to send to it. For a normal kill, send signal 15. For a sure, but rather 
abrupt kill, send signal 9.
.TP 0.5i
.B r
Re-nice a process. You will be prompted for the PID of the task, and the value
to nice it to. Entering a positve value will  cause a process to get niced to 
negative values, and loose priority. If root is running top, a negative value
can be entered, causing a process to get a higher than normal priority.
.TP 0.5i
.B s
Change the delay between updates. You will be prompted to enter the delay time,
in seconds, between updates. Fractional values are recognized down to
microseconds. Entering 0 causes continuous updates. The default 
value is 5 seconds.
.TP 0.5i
.B ^L
Erases are re-draws the screen.

.SH UPDATING
This proc-based top works by reading the files in the proc filesystem,
mounted on /proc.  

.SH NOTES
.PP
Programs swapped out to disk will be shown without command line
arguments.
.PP
%CPU shows the cputime/realtime percentage in the period of time between 
updates. For the first update, a short delay is used, and top itself 
dominates the CPU usage. After that, top will fall back, and a more 
reliable estimate of CPU usage is available
.PP
The SIZE and RSS fields don't count the page tables and the
task_struct of a proc, this is at least 12k of memory that is always
resident. SIZE is the virtual size of the proc (code+data+stack).

.SH BUGS
Does not format the screen correctly if the screen width is less than about 70 
characters. Also, if the screen height is less than 7 lines, formatting is 
incorrect.
.PP
Some handy command line arguments are missing (like -q to run at extra high 
priority).
.SH AUTHOR
.B top
was originally written by Roger Binns, based on Branko Lankester's
(lankeste@fwi.uva.nl) ps program.
Robert Nation (nation@rocket.sanders.lockheed.com re-wrote it significantly to
use the proc filesystem, based on Michael K Johnson's (johnsonm@stolaf.edu) 
proc-based ps program.
