.\"             -*-Nroff-*-
.\"
.TH UPTIME 1 "26 Jan 1993 " "Cohesive Systems" "Linux Programmer's Manual"
.SH NAME
uptime \- Tell how long the system has been running.
.SH SYNOPSIS
uptime
.SH DESCRIPTION
.B "uptime "
gives a one line display of the following information.
The current time,
how long the system has been running,
how many users are currently logged on,
and the system load averages for the past 1, 5, and 15 minutes.
.sp
This is the same information contained in the header line displayed by w(1)

.PP
.SH FILES
.ta
/etc/utmp -- information about who is currently logged on
/etc/proc -- process information
.fi

.SH "SEE ALSO"
ps(1), top(1), utmp(5), w(1)

.SH AUTHORS
.B uptime
was written by Larry Greenfield (greenfie@gauss.rutgers.edu) and
Michael K. Johnson (johnsonm@stolaf.edu).
