.\"             -*-Nroff-*-
.\"
.TH W 1 "26 Jan 1993 " "Cohesive Systems" "Linux Programmer's Manual"
.SH NAME
w \- Show who is logged on and what they are doing.
.SH SYNOPSIS
w \-[hls]
.SH DESCRIPTION
.B "w "
displays information about the users currently on the machine,
and their processes.
The header shows, in this order,  the current time,
how long the system has been running,
how many users are currently logged on,
and the system load averages for the past 1, 5, and 15 minutes.
.sp
The following entries are displayed for each user:
login name, the tty name, login time, idle time, JCPU, PCPU,
and the command line of their current process.
.sp
The JCPU time is the time used by all processes and their children,
attached to the tty.
The PCPU time is the time used by the current process.

.PP
.SH "COMMAND\-LINE OPTIONS"
.TP 0.5i
.B "\-h "
Don't print the header.
.TP 0.5i
.B "\-l "
Use the long format. This is the default.
.TP 0.5i
.B "\-u "
Ignores the username while figuring out the current process and cpu
times.  To demonstrate this, do a "su" and do a "w" and a "w -u".
.TP 0.5i
.B "\-s "
Use the short format.
Don't print the login time,
JCPU or PCPU times,
or the arguments to the current process name.

.SH FILES
.ta
/etc/utmp -- information about who is currently logged on
/etc/proc -- process information
.fi

.SH "SEE ALSO"
free(1), ps(1), top(1), uptime(1), utmp(5), who(1)

.SH AUTHORS
.B w
was written by Larry Greenfield (greenfie@gauss.rutgers.edu) and
Michael K. Johnson (johnsonm@stolaf.edu).
