#! /bin/sh
# convert_to_Xdefaults - convert SunView1 defaults to X Window defaults
#			 (X11 Resource File format) for XView
# 
# convert_to_Xdefaults filename
#
# Output should be placed in a user's ~/.Xdefaults file
# 
cat ${1} | \
 sed -e 's%/sunview/scale%Window.Scale:%g' \
    -e 's%"%%g' \
    -e 's%SunDefaults%!SunDefaults%g' \
    -e 's%#/Menu/Pullright_delta%OpenWindows.DragRightDistance:%g' \
    -e 's%!/Menu/Pullright_delta%OpenWindows.DragRightDistance:%g' \
    -e 's%#/menu/pullright_delta%OpenWindows.DragRightDistance:%g' \
    -e 's%!/menu/pullright_delta%OpenWindows.DragRightDistance:%g' \
    -e 's%#/Sunview/Audible_bell%Alarm.Audible:%g' \
    -e 's%!/Sunview/Audible_bell%Alarm.Audible:%g' \
    -e 's%#/Sunview/audible_bell%Alarm.Audible:%g' \
    -e 's%!/Sunview/audible_bell%Alarm.Audible:%g' \
    -e 's%#/Sunview/Visible_bell%Alarm.Visible:%g' \
    -e 's%!/Sunview/Visible_bell%Alarm.Visible:%g' \
    -e 's%#/Sunview/visible_bell%Alarm.Visible:%g' \
    -e 's%!/Sunview/visible_bell%Alarm.Visible:%g' \
    -e 's%#/Sunview/Alert_jump_cursor%Notice.JumpCursor:%g' \
    -e 's%!/Sunview/Alert_jump_cursor%Notice.JumpCursor:%g' \
    -e 's%#/Sunview/alert_jump_cursor%Notice.JumpCursor:%g' \
    -e 's%!/Sunview/alert_jump_cursor%Notice.JumpCursor:%g' \
    -e 's%#/Sunview/Alert_bell%Notice.BeepCount:%g'  \
    -e 's%!/Sunview/Alert_bell%Notice.BeepCount:%g'  \
    -e 's%#/Sunview/alert_bell%Notice.BeepCount:%g'  \
    -e 's%!/Sunview/alert_bell%Notice.BeepCount:%g'  \
    -e 's%/text/%/Text/%g' \
    -e 's%/tty/%/Tty/%g' \
    -e 's%/Tty/Auto_indent%Text.AutoIndent:%g' \
    -e 's%/Tty/auto_indent%Text.AutoIndent:%g' \
    -e 's%/Tty/Control_chars_use_font%Text.DisplayControlChars:%g' \
    -e 's%/Tty/control_chars_use_font%Text.DisplayControlChars:%g' \
    -e 's%/Tty/Insert_makes_caret_visible%Text.InsertMakesCaretVisible:%g' \
    -e 's%/Tty/insert_makes_caret_visible%Text.InsertMakesCaretVisible:%g' \
    -e 's%/Tty/Append_only_log%Term.EnableEdit:%g' \
    -e 's%/Tty/append_only_log%Term.EnableEdit:%g' \
    -e 's%/Tty/Bold_style%Term.BoldStyle:%g' \
    -e 's%/Tty/bold_style%Term.BoldStyle:%g' \
    -e 's%/Tty/Inverse_mode%Term.InverseStyle:%g' \
    -e 's%/Tty/inverse_mode%Term.InverseStyle:%g' \
    -e 's%/Tty/Underline_mode%Term.UnderlineStyle:%g' \
    -e 's%/Tty/underline_mode%Term.UnderlineStyle:%g' \
    -e 's%/Text/Edit_back_char%Keyboard.DeleteChar:%g' \
    -e 's%/Text/edit_back_char%Keyboard.DeleteChar:%g' \
    -e 's%/Text/Edit_back_word%Keyboard.DeleteWord:%g' \
    -e 's%/Text/edit_back_word%Keyboard.DeleteWord:%g' \
    -e 's%/Text/Edit_back_line%Keyboard.DeleteLine:%g' \
    -e 's%/Text/edit_back_line%Keyboard.DeleteLine:%g' \
    -e 's%/Text/multi_click_timeout%!OpenWindows.MultiClickTimeout:now in tenths of seconds rather than millisecs%g' \
    -e 's%/Text/Multi_click_timeout%!OpenWindows.MultiClickTimeout:now in tenths of seconds rather than millisecs%g' \
    -e 's%/Tty/Checkpoint_frequency%Term.CheckpointFrequency:%g' \
    -e 's%/Tty/checkpoint_frequency%Term.CheckpointFrequency:%g' \
    -e 's%/Tty/Retained%Text.Retained:%g' \
    -e 's%/Tty/retained%Text.Retained:%g' \
    -e 's%/Tty/Text_wraparound_size%Term.MaxLogFileSize:%g' \
    -e 's%/Tty/text_wraparound_size%Term.MaxLogFileSize:%g' \
    -e 's%/Text/Scrollable%Text.EnableScrollbar:%g' \
    -e 's%/Text/scrollable%Text.EnableScrollbar:%g' \
    -e 's%/Text/Again_limit%Text.AgainLimit:%g' \
    -e 's%/Text/again_limit%Text.AgainLimit:%g' \
    -e 's%/Text/Auto_indent%Text.AutoIndent:%g' \
    -e 's%/Text/auto_indent%Text.AutoIndent:%g' \
    -e 's%/Text/Auto_scroll_by%Text.AutoScrollBy:%g' \
    -e 's%/Text/auto_scroll_by%Text.AutoScrollBy:%g' \
    -e 's%/Text/Blink_caret%Text.BlinkCaret:%g' \
    -e 's%/Text/blink_caret%Text.BlinkCaret:%g' \
    -e 's%/Text/Checkpoint_frequency%Text.CheckpointFrequency:%g' \
    -e 's%/Text/checkpoint_frequency%Text.CheckpointFrequency:%g' \
    -e 's%/Text/Confirm_overwrite%Text.ConfirmOverwrite:%g' \
    -e 's%/Text/confirm_overwrite%Text.ConfirmOverwrite:%g' \
    -e 's%/Text/Control_chars_use_font%Text.DisplayControlChars:%g' \
    -e 's%/Text/control_chars_use_font%Text.DisplayControlChars:%g' \
    -e 's%/Text/Insert_makes_caret_visible%Text.InsertMakesCaretVisible:%g' \
    -e 's%/Text/insert_makes_caret_visible%Text.InsertMakesCaretVisible:%g' \
    -e 's%/Text/Long_line_break_mode%Text.LineBreak:%g' \
    -e 's%/Text/long_line_break_mode%Text.LineBreak:%g' \
    -e 's%/Text/Lower_context%Text.Margin.Bottom:%g' \
    -e 's%/Text/lower_context%Text.Margin.Bottom:%g' \
    -e 's%/Text/Memory_maximum%Text.MaxDocumentSize:%g' \
    -e 's%/Text/Memory_Maximum%Text.MaxDocumentSize:%g' \
    -e 's%/Text/memory_maximum%Text.MaxDocumentSize:%g' \
    -e 's%/Text/Multi_click_space%Mouse.Multiclick.Space:%g' \
    -e 's%/Text/multi_click_space%Mouse.Multiclick.Space:%g' \
    -e 's%/Text/Multi_click_timeout%Mouse.Multiclick.Timeout:%g' \
    -e 's%/Text/multi_click_timeout%Mouse.Multiclick.Timeout:%g' \
    -e 's%/Text/Store_changes_file%Text.StoreChangesFile:%g' \
    -e 's%/Text/store_changes_file%Text.StoreChangesFile:%g' \
    -e 's%/Text/Upper_context%Text.Margin.Top:%g' \
    -e 's%/Text/upper_context%Text.Margin.Top:%g' \
    -e 's%/Text/Left_margin%Text.Margin.Left:%g' \
    -e 's%/Text/left_margin%Text.Margin.Left:%g' \
    -e 's%/Text/Right_margin%Text.Margin.Right:%g' \
    -e 's%/Text/right_margin%Text.Margin.Right:%g' \
    -e 's%/Text/Tab_width%Text.TabWidth:%g' \
    -e 's%/Text/tab_width%Text.TabWidth:%g' \
    -e 's%/Text/Extras_menu_filename%Text.ExtrasMenuFilename:%g' \
    -e 's%/Text/extras_menu_filename%Text.ExtrasMenuFilename:%g' \
    -e 's%/Text/Retained%Text.Retained:%g' \
    -e 's%/Text/retained%Text.Retained:%g' \
    -e 's%/Text/Contents%! N/A in OPEN LOOK: no scratch window  /Text/Contents%g' \
    -e 's%/Text/contents%! N/A in OPEN LOOK: no scratch window  /Text/Contents%g' \
    -e 's%/Input/Keymap_Directory%! N/A in OPEN LOOK: not a Kernel-based window system  /Input/Keymap_Directory%g' | \
 sed -e 's,^/,!/,'
