.TH BMS 1 "20 Jul 1991" "MandelSpawn 0.06"
.SH NAME 
bms \- Batch MandelSpawn, a network Mandelbrot program.
.SH SYNOPSIS  
.B bms
[
.B \-options 
] ...
.SH DESCRIPTION  
.I Bms
is a program for making pictures of the Mandelbrot and Julia sets.
It is a batch-mode version of the interactive, X-based
.I xms
program (see
.IR xms (1))
for full information).
.PP
Bms writes the picture on its standard output in Portable Greymap
.I (pgm) 
format.  The iteration counts are used directly as 
greyscale pixel values, so the interior of the Mandelbrot set will appear
white, not black.  The picture can be further manipulated using the
tools from Jef Poskanzer's PBMPLUS image processing and conversion
package.  A typical example is the pipeline
.PP
	bms -iterations 256 -width 600 -height 400 | 
.br
		pnminvert |
.br
		pgmtops -rle |
.br
		lpr -Pps
.PP
which can be used to print a black-on-white Mandelbrot image on a
PostScript printer.
.PP
.SH "COMMAND LINE OPTIONS"
.PP
Bms supports the following command line options:
.IP "\fB\-iterations\fP \fIn\fP"
Specifies the maximum number of iterations.  The default is 250.
.IP "\fB\-x\fP, \fB\-y\fP, \fB\-range\fP"
Specify the center coordinates and horizontal width, respectively, of
the part of the Mandelbrot or Julia set to be calculated.
.IP "\fB\-julia\fP"
Calculate a Julia set instead of the Mandelbrot
set.  The "\fB\-cx\fP" and "\fB\-cy\fP" options may be used to
choose the \fIc\fP parameter for the Julia set.
.IP "\fB\-verbose\fP"
Print a period on standard error for each reply received from a computation
server.
.IP "\fB\-statistics\fP"
Print performance statistics on standard error after finishing 
the calculations.
.IP "\fB\-ascii\fP"
Force ASCII format for the output file.
.PP
.SH BUGS
Bms normally generates binary
.I pgm
output,
but when the iteration count exceeds 256 it reverts to
the ASCII version of the file format.
This causes a large increase in file size and an even
larger increase in CPU usage.
.SH FILES
.if n .ta 2.5i
.if t .ta 2i
/usr/local/etc/mslaves	list of computation server hosts
.br
$HOME/.mslaves	per-user override of the above
.PP
.SH "SEE ALSO"
xms(1), mslaved(8), mslavedc(8), enslave(1), pgm(1), pnm(1)
.PP
.SH COPYRIGHT
.if n Copyright (C) 1990, 1991 Andreas Gustafsson (gson@niksula.hut.fi)
.if t Copyright \(co 1990, 1991 Andreas Gustafsson (gson@niksula.hut.fi)
